import { mutation } from "./_generated/server";
import { v } from "convex/values";

const loc = (en: string, fr: string) => ({ en, fr });

const DUA_CATEGORIES = [
  { name: loc("Morning & Evening", "Matin et Soir"), description: loc("Duas for morning and evening remembrance", "Dua pour le souvenir du matin et du soir"), icon: "Sun", sortOrder: 1 },
  { name: loc("Before/After Prayer", "Avant/Après la prière"), description: loc("Duas recited before and after Salah", "Dua récitées avant et après la prière"), icon: "Clock", sortOrder: 2 },
  { name: loc("Travel", "Voyage"), description: loc("Duas for traveling and journey protection", "Dua pour la protection en voyage"), icon: "Plane", sortOrder: 3 },
  { name: loc("Eating & Drinking", "Manger et Boire"), description: loc("Duas before and after meals", "Dua avant et après les repas"), icon: "Utensils", sortOrder: 4 },
  { name: loc("Entering & Leaving Home", "Entrer et Sortir de la maison"), description: loc("Duas for entering and leaving your home", "Dua pour entrer et sortir de la maison"), icon: "Home", sortOrder: 5 },
  { name: loc("Distress & Seeking Help", "Détresse et recherche d'aide"), description: loc("Duas in times of difficulty and need", "Dua en temps de difficulté et de besoin"), icon: "HeartHandshake", sortOrder: 6 },
  { name: loc("Gratitude & Praise", "Gratitude et Louange"), description: loc("Duas of thankfulness and praise to Allah", "Dua de gratitude et de louange à Allah"), icon: "Sparkles", sortOrder: 7 },
  { name: loc("Protection", "Protection"), description: loc("Duas for seeking Allah's protection", "Dua pour demander la protection d'Allah"), icon: "Shield", sortOrder: 8 },
  { name: loc("For Parents", "Pour les parents"), description: loc("Duas for parents' wellbeing", "Dua pour le bien-être des parents"), icon: "Users", sortOrder: 9 },
  { name: loc("For Children", "Pour les enfants"), description: loc("Duas for children's guidance and protection", "Dua pour la guidance et la protection des enfants"), icon: "Baby", sortOrder: 10 },
  { name: loc("For Knowledge", "Pour le savoir"), description: loc("Duas for seeking knowledge", "Dua pour la recherche du savoir"), icon: "GraduationCap", sortOrder: 11 },
  { name: loc("For Health", "Pour la santé"), description: loc("Duas for health and wellbeing", "Dua pour la santé et le bien-être"), icon: "Activity", sortOrder: 12 },
];

const AZKAR_CATEGORIES = [
  { name: loc("Morning Adhkar", "Adhkar du matin"), description: loc("Morning remembrance after Fajr prayer", "Souvenir du matin après la prière Fajr"), type: "morning" as const, sortOrder: 1 },
  { name: loc("Evening Adhkar", "Adhkar du soir"), description: loc("Evening remembrance after Maghrib prayer", "Souvenir du soir après la prière Maghrib"), type: "evening" as const, sortOrder: 2 },
  { name: loc("Before Sleep", "Avant le sommeil"), description: loc("Adhkar before going to sleep", "Adhkar avant de dormir"), type: "sleep" as const, sortOrder: 3 },
  { name: loc("After Prayer", "Après la prière"), description: loc("Adhkar after each obligatory prayer", "Adhkar après chaque prière obligatoire"), type: "generic" as const, sortOrder: 4 },
  { name: loc("Istighfar", "Istighfar"), description: loc("Seeking forgiveness from Allah", "Demande de pardon à Allah"), type: "generic" as const, sortOrder: 5 },
  { name: loc("Salawat on the Prophet", "Salawat sur le Prophète"), description: loc("Sending blessings upon the Prophet Muhammad", "Envoi de bénédictions sur le Prophète Muhammad"), type: "generic" as const, sortOrder: 6 },
];

const DUAS = [
  // Category 1: Morning & Evening
  { catIdx: 0, title: loc("Morning Adhkar", "Adhkar du matin"), arabicText: "أَسْبَحُ بِحَمْدِ اللَّهِ وَبِحَمْدِ اللَّهِ أَمْسَيْتُ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ", transliteration: "Asbahtu bihamdillahi wa bihamdillahi amsayt, la ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer", translation: loc("I enter the morning with Allah's praise, and with Allah's praise I enter the evening. None has the right to be worshipped except Allah alone, with no partner. To Him belongs sovereignty and to Him belongs praise, and He has power over all things.", "J'entre dans la matinée avec la louange d'Allah, et avec la louange d'Allah j'entre dans la soirée. Nul n'a le droit d'être adoré excepté Allah seul, sans associé. À Lui appartient la souveraineté et à Lui appartient la louange, et Il a le pouvoir sur toute chose."), source: "Abu Dawud #5089", occasions: ["morning", "evening"] },
  { catIdx: 0, title: loc("Du'a of the Morning", "Dua du matin"), arabicText: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ", transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu, wa ilaykin nushoor", translation: loc("O Allah, by You we enter the morning, and by You we enter the evening. By You we live, and by You we die, and to You is the resurrection.", "Ô Allah, par Toi nous entrons dans la matinée, et par Toi nous entrons dans la soirée. Par Toi nous vivons, et par Toi nous mourons, et vers Toi est la résurrection."), source: "Sunan at-Tirmidhi #5", occasions: ["morning"] },
  { catIdx: 0, title: loc("Du'a of the Evening", "Dua du soir"), arabicText: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ", transliteration: "Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namootu, wa ilaykal maseer", translation: loc("O Allah, by You we enter the evening, and by You we enter the morning. By You we live, and by You we die, and to You is our return.", "Ô Allah, par Toi nous entrons dans la soirée, et par Toi nous entrons dans la matinée. Par Toi nous vivons, et par Toi nous mourons, et vers Toi est notre retour."), source: "Sunan at-Tirmidhi #5", occasions: ["evening"] },
  { catIdx: 0, title: loc("Ayat al-Kursi", "Ayat al-Kursi"), arabicText: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ، لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ، لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ، مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ، يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ، وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ، وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ، وَلَا يَئُودُهُ حِفْظُهُمَا، وَهُوَ الْعَلِيُّ الْعَظِيمُ", transliteration: "Allahu la ilaha illa huwal hayyul qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis samawati wa ma fil ard, man dhal ladhi yashfa'u indahu illa bi idhnihi, ya'lamu ma bayna aydeehim wa ma khalfahum, wa la yuheetuna bi shay'in min ilmihi illa bima sha'a, wasi'a kursiyyuhus samawati wal ard, wa la ya'uduhu hifzuhuma, wa huwal aliyyul adheem", translation: loc("Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Throne extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.", "Allah ! Il n'y a de dieu que Lui, le Vivant, le Subsistant. Ni sommeil ni sommeil ne L'atteignent. À Lui appartient ce qui est dans les cieux et ce qui est sur la terre. Qui peut intercéder auprès de Lui, si ce n'est par Sa permission ? Il connaît ce qui est devant eux et ce qui est derrière eux, et ils n'encompassent rien de Sa science si ce n'est ce qu'Il veut. Son Trône s'étend sur les cieux et la terre, et leur conservation ne Le fatigue pas. Et Il est le Très-Haut, le Très-Grand."), source: "Quran 2:255, Bukhari #5010", occasions: ["morning", "evening"] },
  { catIdx: 0, title: loc("Protection from Shaytan", "Protection contre le Shaytan"), arabicText: "أَعُوذُ بِاللَّهِ مِنْ الشَّيْطَانِ الرَّجِيمِ، اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ، لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ", transliteration: "A'udhu billahi minash shaytanir rajim, Allahu la ilaha illa huwal hayyul qayyum, la ta'khudhuhu sinatun wa la nawm", translation: loc("I seek refuge with Allah from the accursed Shaytan. Allah! There is no deity except Him, the Ever-Living, the Sustainer. Neither drowsiness overtakes Him nor sleep.", "Je demande refuge auprès d'Allah contre le Shaytan maudit. Allah ! Il n'y a de dieu que Lui, le Vivant, le Subsistant. Ni sommeil ni sommeil ne L'atteignent."), source: "Bukhari #5010", occasions: ["morning", "evening"] },

  // Category 2: Before/After Prayer
  { catIdx: 1, title: loc("Takbir al-Ihram", "Takbir al-Ihram"), arabicText: "اللَّهُ أَكْبَرُ كَبِيرًا، وَالْحَمْدُ لِلَّهِ كَثِيرًا، وَسُبْحَانَ اللَّهِ بُكْرَةً وَأَصِيلًا", transliteration: "Allahu Akbar kabira, wal hamdu lillahi katheera, wa subhanallahi bukratan wa aseela", translation: loc("Allah is the Greatest, and praise be to Allah in abundance. Glorified is Allah in the morning and evening.", "Allah est le Plus Grand, et la louange est à Allah en abondance. Gloire à Allah au matin et au soir."), source: "Muslim #599", occasions: ["before_prayer"] },
  { catIdx: 1, title: loc("Du'a before Wudu", "Dua avant l'ablution"), arabicText: "اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ، وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", transliteration: "Allahummaj'alni minat tawwabeen, waj'alni minal mutatahireen", translation: loc("O Allah, make me among those who repent and make me among those who purify themselves.", "Ô Allah, fais-moi partie de ceux qui se repentent et fais-moi partie de ceux qui se purifient."), source: "Tirmidhi #55", occasions: ["before_prayer"] },
  { catIdx: 1, title: loc("Dua after Wudu", "Dua après l'ablution"), arabicText: "أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ، وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ", transliteration: "Ashhadu an la ilaha illallahu wahdahu la shareeka lah, wa ashhadu anna muhammadan abduhu wa rasooluh, Allahummaj'alni minat tawwabeen, waj'alni minal mutatahireen", translation: loc("I bear witness that none has the right to be worshipped except Allah alone, with no partner, and I bear witness that Muhammad is His servant and Messenger. O Allah, make me among those who repent and those who purify themselves.", "J'atteste qu'il n'y a de dieu qu'Allah seul, sans associé, et j'atteste que Muhammad est Son serviteur et Son messager. Ô Allah, fais-moi partie de ceux qui se repentent et de ceux qui se purifient."), source: "Abu Dawud #101", occasions: ["after_prayer"] },
  { catIdx: 1, title: loc("Du'a Qunut", "Dua Qunut"), arabicText: "اللَّهُمَّ اهْدِنِي فِيمَنْ هَدَيْتَ، وَعَافِنِي فِيمَنْ عَافَيْتَ، وَتَوَلَّنِي فِيمَنْ تَوَلَّيْتَ، وَبَارِكْ لِي فِيمَا أَعْطَيْتَ، وَقِنِي شَرَّ مَا قَضَيْتَ، فَإِنَّكَ تَقْضِي وَلَا يُقْضَى عَلَيْكَ، وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ، وَلَا يَعِزُّ مَنْ عَادَيْتَ، تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ", transliteration: "Allahumma hdini fiman hadayt, wa 'afini fiman 'afayt, wa tawallani fiman tawallayt, wa barik li fima a'tayt, wa qini sharra ma qadayt, fa innaka taqdi wa la yuqda 'alayk, wa innahu la yadhillu man walayt, wa la ya'izzu man 'adayt, tabarakta rabbana wa ta'alayt", translation: loc("O Allah, guide me among those You have guided, grant me health among those You have granted health, take care of me among those You take care of, bless me in what You have given me, and protect me from the evil of what You have decreed, for You decree and none can decree against You. Truly, none is humiliated whom You befriend, and none is honored whom You oppose. Blessed are You, our Lord, and Exalted.", "Ô Allah, guide-moi parmi ceux que Tu as guidés, accorde-moi la santé parmi ceux à qui Tu l'as accordée, prends-moi en charge parmi ceux que Tu prends en charge, bénis-moi dans ce que Tu m'as donné, et protège-moi du mal de ce que Tu as décrété, car Tu décides et personne ne décide contre Toi. En vérité, nul n'est humilié que celui que Tu abandonnes, et nul n'est honoré que celui que Tu opposes. Tu es béni, notre Seigneur, et Tu es élevé."), source: "Abu Dawud #1425", occasions: ["after_prayer"] },
  { catIdx: 1, title: loc("Dua after Tashahhud and before Taslim", "Dua entre le Tashahhud et le Taslim"), arabicText: "اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ، وَارْحَمْنِي إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ", transliteration: "Allahumma inni zalamtu nafsi zulman katheera, wa la yaghfirudh dhunuba illa anta, faghfir li maghfiratan min indik, warhamni innaka antal ghafoorur raheem", translation: loc("O Allah, I have wronged myself greatly, and none forgives sins except You. So grant me forgiveness from Yourself and have mercy upon me, for indeed You are the Forgiving, the Merciful.", "Ô Allah, j'ai fait grandement du tort à moi-même, et nul ne pardonne les péchés que Toi. Alors pardonne-moi un pardon de Ta part et aie pitié de moi, car Tu es certes le Pardonneur, le Miséricordieux."), source: "Bukhari #834", occasions: ["after_prayer"] },

  // Category 3: Travel
  { catIdx: 2, title: loc("Du'a for Travel", "Dua de voyage"), arabicText: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ", transliteration: "Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrineen, wa inna ila rabbina la munqaliboon", translation: loc("Glory be to Him who has subjected this to us, and we could not have subjugated it ourselves. And indeed, to our Lord we will return.", "Gloire à Celui qui nous a soumis cela, et nous ne l'aurions jamais pu par nous-mêmes. Et certes, à notre Seigneur, nous retournerons."), source: "Quran 43:13-14", occasions: ["travel"] },
  { catIdx: 2, title: loc("Travel Du'a (Complete)", "Dua de voyage complète"), arabicText: "اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ، وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ، اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَٰذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَٰذَا وَاطْوِ عَنَّا بُعْدَهُ، اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ، وَالْخَلِيفَةُ فِي الْأَهْلِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَثَاءِ السَّفَرِ وَكَآبَةِ الْمُنْقَلَبِ، وَمِنَ الْحَوْرِ بَعْدَ الْكَوْرِ، وَمِنَ الدُّعَاءِ إِلَى الْمَصِيبَةِ", transliteration: "Allahu Akbar, Allahu Akbar, Allahu Akbar, Subhanalladhi sakhkhara lana hadha wa ma kunna lahu muqrineen, wa inna ila rabbina la munqaliboon, Allahumma inni nas'aluka fi safarina hadhal birra wat taqwa, wa minal amali ma tarda, Allahumma hawwin 'alayna safarana hadha watwi 'anna bu'dahu, Allahumma antas sahibu fis safar, wal khaleefatu fil ahel, Allahumma inni a'udhu bika min 'athais safar wa ka'abatil munqalab, wa minad du'ail mazeeba", translation: loc("Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. Glorified is He who has subjected this to us and we could not have done it ourselves. And to our Lord we will return. O Allah, we ask You in this journey for righteousness and piety, and for deeds that are pleasing to You. O Allah, make this journey easy for us and shorten its distance. O Allah, You are our Companion in travel and our Guardian of the family. O Allah, I seek refuge in You from the hardships of travel and distress of return.", "Allah est le Plus Grand, Allah est le Plus Grand, Allah est le Plus Grand. Gloire à Celui qui nous a soumis cela, et nous ne l'aurions jamais pu. À notre Seigneur nous retournerons. Ô Allah, nous Te demandons dans ce voyage la piété et la crainte d'Allah, et les œuvres qui Te satisfont. Ô Allah, facilite-nous ce voyage et raccourcis sa distance. Ô Allah, Tu es le Compagnon en voyage et le Protecteur de la famille."), source: "Muslim #1342", occasions: ["travel"] },
  { catIdx: 2, title: loc("Return from Travel", "Retour du voyage"), arabicText: "آيِبُونَ، تَائِبُونَ، عَابِدُونَ، لِرَبِّنَا حَامِدُونَ", transliteration: "Ayeboona, taeboona, abidoona, li rabbina hamidoon", translation: loc("We return, repent, worship, and praise our Lord.", "Nous revenons, nous nous repentons, nous adorons et nous louons notre Seigneur."), source: "Muslim #1345", occasions: ["travel"] },

  // Category 4: Eating & Drinking
  { catIdx: 3, title: loc("Du'a before Eating", "Dua avant de manger"), arabicText: "بِسْمِ اللَّهِ، وَعَلَى بَرَكَةِ اللَّهِ", transliteration: "Bismillahi, wa 'ala barakatillah", translation: loc("In the name of Allah, and with the blessings of Allah.", "Au nom d'Allah, et avec la bénédiction d'Allah."), source: "Abu Dawud #3767", occasions: ["eating"] },
  { catIdx: 3, title: loc("Du'a after Eating", "Dua après avoir mangé"), arabicText: "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا، وَجَعَلَنَا مُسْلِمِينَ", transliteration: "Alhamdu lillahil ladhi at'amana wa saqana, wa ja'alana muslimeen", translation: loc("Praise be to Allah who fed us and gave us drink and made us Muslims.", "Louange à Allah qui nous a nourris et désaltérés et qui nous a faits musulmans."), source: "Abu Dawud #3850", occasions: ["eating"] },
  { catIdx: 3, title: loc("Du'a when forget to say Bismillah", "Dua quand on oublie de dire Bismillah"), arabicText: "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ", transliteration: "Bismillahi awwalahu wa akhirahu", translation: loc("In the name of Allah, at the beginning and at the end.", "Au nom d'Allah, au commencement et à la fin."), source: "Abu Dawud #3850", occasions: ["eating"] },
  { catIdx: 3, title: loc("Du'a when disliking food", "Dua quand on n'aime pas la nourriture"), arabicText: "اللَّهُمَّ أَطْعِمْنِي خَيْرًا مِنْهُ، وَأَسْقِنِي خَيْرًا مِنْهُ", transliteration: "Allahumma at'imni khayran minhu, wa asqini khayran minhu", translation: loc("O Allah, feed me something better than it, and give me drink something better than it.", "Ô Allah, nourris-moi de quelque chose de meilleur, et désaltère-moi de quelque chose de meilleur."), source: "Tirmidhi #3456", occasions: ["eating"] },

  // Category 5: Entering & Leaving Home
  { catIdx: 4, title: loc("Du'a before Entering Home", "Dua avant d'entrer à la maison"), arabicText: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا", transliteration: "Bismillahi walajna, wa bismillahi kharajna, wa 'alallahi rabbina tawakkalna", translation: loc("In the name of Allah we enter, in the name of Allah we leave, and upon Allah, our Lord, we rely.", "Au nom d'Allah nous entrons, au nom d'Allah nous sortons, et sur Allah, notre Seigneur, nous nous appuyons."), source: "Abu Dawud #5095", occasions: ["entering_home"] },
  { catIdx: 4, title: loc("Du'a when Entering Home", "Dua en entrant à la maison"), arabicText: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ، بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا", transliteration: "Assalamu alaykum wa rahmatullah, bismillahi walajna, wa bismillahi kharajna, wa 'alallahi rabbina tawakkalna", translation: loc("Peace be upon you and the mercy of Allah. In the name of Allah we enter, in the name of Allah we leave, and upon Allah, our Lord, we rely.", "Que la paix et la miséricordes d'Allah soient sur vous. Au nom d'Allah nous entrons, au nom d'Allah nous sortons, et sur Allah, notre Seigneur, nous nous appuyons."), source: "Abu Dawud #5096", occasions: ["entering_home"] },
  { catIdx: 4, title: loc("Du'a when Leaving Home", "Dua en sortant de la maison"), arabicText: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "Bismillahi, tawakkaltu 'alallahi, wa la hawla wa la quwwata illa billah", translation: loc("In the name of Allah, I rely on Allah, and there is no power nor might except with Allah.", "Au nom d'Allah, je m'en remets à Allah, et il n'y a ni force ni puissance si ce n'est avec Allah."), source: "Abu Dawud #5095", occasions: ["leaving_home"] },
  { catIdx: 4, title: loc("Entering Home Greeting", "Salutation en entrant"), arabicText: "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ", transliteration: "Assalamu alaykum wa rahmatullah", translation: loc("Peace be upon you and the mercy of Allah.", "Que la paix et la miséricordes d'Allah soient sur vous."), source: "Bukhari #6255", occasions: ["entering_home"] },

  // Category 6: Distress & Seeking Help
  { catIdx: 5, title: loc("Du'a of Distress", "Dua de détresse"), arabicText: "لَا إِلَٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ، لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ، لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ السَّمَاوَاتِ وَرَبُّ الْأَرْضِ، وَرَبُّ الْعَرْشِ الْكَرِيمِ", transliteration: "La ilaha illallahul adheemul haleem, la ilaha illallahu rabbul arshil adheem, la ilaha illallahu rabbus samawati wa rabbul ard, wa rabbul arshil kareem", translation: loc("None has the right to be worshipped except Allah, the Almighty, the Forbearing. None has the right to be worshipped except Allah, Lord of the Magnificent Throne. None has the right to be worshipped except Allah, Lord of the heavens and Lord of the earth, and Lord of the Noble Throne.", "Nul n'a le droit d'être adoré excepté Allah, le Tout-Puissant, le Compatissant. Nul n'a le droit d'être adoré excepté Allah, le Seigneur du Trône Magnifique. Nul n'a le droit d'être adoré excepté Allah, le Seigneur des cieux et le Seigneur de la terre, et le Seigneur du Trône Noble."), source: "Bukhari #6317", occasions: ["distress"] },
  { catIdx: 5, title: loc("Du'a of Yunus", "Dua de Younous"), arabicText: "لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ، إِنِّي كُنْتُ مِنَ الظَّالِمِينَ", transliteration: "La ilaha illa anta subhanaka, inni kuntu minaz zalimeen", translation: loc("None has the right to be worshipped except You, Glorified are You. Indeed, I have been of the wrongdoers.", "Nul n'a le droit d'être adoré excepté Toi, Tu es Glorifié. Certes, j'ai été parmi les injustes."), source: "Quran 21:87, Bukhari #6331", occasions: ["distress", "seeking_help"] },
  { catIdx: 5, title: loc("Du'a for Ease", "Dua pour l'aisance"), arabicText: "اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا", transliteration: "Allahumma la sahla illa ma ja'alta sahla, wa anta taj'alul hazna idha sha'ta sahla", translation: loc("O Allah, there is no ease except what You make easy, and You make grief easy when You will.", "Ô Allah, il n'y a d'aisance que ce que Tu rends aisé, et Tu rends le chagrin aisé quand Tu le veux."), source: "Ibn Hibban #974", occasions: ["distress", "seeking_help"] },
  { catIdx: 5, title: loc("Du'a for Anxiety", "Dua pour l'anxiété"), arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ", transliteration: "Allahumma inni a'udhu bika minal hammi wal huzan, wa a'udhu bika minal ajzi wal kasal, wa a'udhu bika minal jubni wal bukhli, wa a'udhu bika ghalabatid dayni wa qahrir rijal", translation: loc("O Allah, I seek refuge in You from worry and grief, from helplessness and laziness, from cowardice and miserliness, and from being overcome by debt and being overpowered by people.", "Ô Allah, je cherche refuge auprès de Toi contre l'inquiétude et le chagrin, contre l'impuissance et la paresse, contre la lâcheté et l'avarice, et contre la domination des dettes et des hommes."), source: "Abu Dawud #5090", occasions: ["distress"] },

  // Category 7: Gratitude & Praise
  { catIdx: 6, title: loc("Du'a for Good", "Dua pour le bien"), arabicText: "اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ", transliteration: "Allahumma la mani'a lima a'tayt, wa la mu'tiya lima mana't, wa la yanfa'u dhal jaddi minkal jadd", translation: loc("O Allah, none can withhold what You give, and none can give what You withhold, and no wealth or power can benefit anyone against You.", "Ô Allah, nul ne peut retenir ce que Tu donnes, et nul ne peut donner ce que Tu retiens, et aucune richesse ni puissance ne profite contre Toi."), source: "Bukhari #844", occasions: ["gratitude"] },
  { catIdx: 6, title: loc("Du'a for Gratitude", "Dua de gratitude"), arabicText: "اللَّهُمَّ مَا أَصْبَحَ بِي مِنْ نِعْمَةٍ أَوْ بِأَحَدٍ مِنْ خَلْقِكَ فَمِنْكَ وَحْدَكَ لَا شَرِيكَ لَكَ، فَلَكَ الْحَمْدُ وَلَكَ الشُّكْرُ", transliteration: "Allahumma ma asbaha bi min ni'matin aw bi ahadin min khalqika faminka wahdaka la shareeka lak, falakal hamdu wa lakash shukr", translation: loc("O Allah, whatever blessing has been with me this morning or with any of Your creation, it is from You alone with no partner. So to You belongs all praise and to You belongs all gratitude.", "Ô Allah, toute bénédiction qui m'a atteint ce matin ou qui a atteint l'une de Tes créatures, vient de Toi seul sans associé. À Toi donc la louange et à Toi la gratitude."), source: "Abu Dawud #5089", occasions: ["gratitude"] },

  // Category 8: Protection
  { catIdx: 7, title: loc("Mu'awwidhatayn", "Mu'awwidhatayn"), arabicText: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ، مِنْ شَرِّ مَا خَلَقَ، وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ، وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ", transliteration: "Qul a'udhu bi rabbil falaq, min sharri ma khalaq, wa min sharri ghasiqin idha waqab, wa min sharrin naffathati fil uqad, wa min sharri hasidin idha hasad", translation: loc("Say: I seek refuge in the Lord of daybreak, from the evil of that which He created, from the evil of darkness when it settles, from the evil of those who blow on knots, and from the evil of an envier when he envies.", "Dis : Je demande refuge auprès du Seigneur de l'aube, contre le mal de ce qu'Il a créé, contre le mal de l'obscurité quand elle s'installe, contre le mal de celles qui soufflent sur les nœuds, et contre le mal de l'envieux quand il envie."), source: "Quran 113:1-5", occasions: ["protection"] },
  { catIdx: 7, title: loc("Three Quls", "Les trois Qul"), arabicText: "قُلْ هُوَ اللَّهُ أَحَدٌ، اللَّهُ الصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ", transliteration: "Qul huwallahu ahad, Allahus samad, lam yalid wa lam yoolad, wa lam yakul lahoo kufuwan ahad", translation: loc("Say: He is Allah, the One. Allah, the Eternal Refuge. He neither begets nor is born. Nor is there to Him any equivalent.", "Dis : Il est Allah, l'Un. Allah, le Refuges Éternel. Il n'engendre ni n'est engendré. Et nul n'est Lui équivalent."), source: "Quran 112:1-4", occasions: ["protection", "morning", "evening"] },
  { catIdx: 7, title: loc("Du'a for Protection from Evil Eye", "Dua contre le mauvais œil"), arabicText: "أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ", transliteration: "A'udhu bikalimatillahit tammati min sharri ma khalaq", translation: loc("I seek refuge in the perfect words of Allah from the evil of what He has created.", "Je demande refuge dans les paroles parfaites d'Allah contre le mal de ce qu'Il a créé."), source: "Muslim #2708", occasions: ["protection"] },
  { catIdx: 7, title: loc("Morning & Evening Protection", "Protection matin et soir"), arabicText: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahil ladhi la yadurru ma'asmihi shai'un fil ardi wa la fis sama'i, wa huwas samee'ul aleem", translation: loc("In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.", "Au nom d'Allah, avec le nom duquel rien sur terre ni dans les cieux ne peut nuire, et Il est l'Audient, l'Omniscient."), source: "Abu Dawud #5088", occasions: ["morning", "evening", "protection"] },

  // Category 9: For Parents
  { catIdx: 8, title: loc("Du'a for Parents", "Dua pour les parents"), arabicText: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", transliteration: "Rabbi rhamhuma kama rabbayani sagheera", translation: loc("My Lord, have mercy upon them as they raised me when I was small.", "Mon Seigneur, aie pitié d'eux comme ils m'ont élevé lorsque j'étais petit."), source: "Quran 17:24", occasions: ["for_parents"] },
  { catIdx: 8, title: loc("Comprehensive Du'a for Parents", "Dua complète pour les parents"), arabicText: "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا، وَأَوْزِعْهُمَا أَنْ يُشْكُرَانِ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَىٰ وَالِدَيَّ، وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ، وَأَصْلِحْ لِي فِي ذُرِّيَّتِي", transliteration: "Rabbi rhamhuma kama rabbayani sagheera, wa awzi'humaa an yushkura ni'matakal lati an'amta alayya wa ala walidayya, wa an a'mala salihan tardahu, wa aslih li fi dhurriyyati", translation: loc("My Lord, have mercy on them as they raised me when I was small. Inspire them to be grateful for Your blessing upon me and upon my parents, and that I do good works that please You, and reform my offspring.", "Mon Seigneur, aie pitié d'eux comme ils m'ont élevé lorsque j'étais petit. Inspire-leur la gratitude pour Ta bénédiction sur moi et sur mes parents, et que je fasse de bonnes œuvres qui Te satisfont, et réforme ma descendance."), source: "Quran 17:24-26", occasions: ["for_parents"] },

  // Category 10: For Children
  { catIdx: 9, title: loc("Du'a for Righteous Children", "Dua pour des enfants pieux"), arabicText: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ", transliteration: "Rabbi hab li minas salihin", translation: loc("My Lord, grant me from among the righteous.", "Mon Seigneur, accorde-moi parmi les vertueux."), source: "Quran 37:100", occasions: ["for_children"] },
  { catIdx: 9, title: loc("Du'a for Children's Protection", "Dua pour la protection des enfants"), arabicText: "أُعِيذُهُمَا بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ، وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ", transliteration: "U'eethuhuma bikalimatillahit tammati min kulli shaytaniw wa hammatin, wa min kulli aynin lammah", translation: loc("I seek protection for them with the perfect words of Allah from every devil, poisonous creature, and every evil eye.", "Je demande protection pour eux avec les paroles parfaites d'Allah contre chaque diable, chaque créature venimeuse et chaque mauvais œil."), source: "Bukhari #5750", occasions: ["for_children"] },

  // Category 11: For Knowledge
  { catIdx: 10, title: loc("Du'a for Knowledge", "Dua pour le savoir"), arabicText: "رَبِّ زِدْنِي عِلْمًا", transliteration: "Rabbi zidni ilma", translation: loc("My Lord, increase me in knowledge.", "Mon Seigneur, augmente-moi en savoir."), source: "Quran 20:114", occasions: ["knowledge"] },
  { catIdx: 10, title: loc("Du'a before Studying", "Dua avant d'étudier"), arabicText: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي، وَعَلِّمْنِي مَا يَنْفَعُنِي، وَزِدْنِي عِلْمًا", transliteration: "Allahummanfa'ni bima 'allamtani, wa 'allimni ma yanfa'uni, wa zidni ilma", translation: loc("O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.", "Ô Allah, fais-moi profiter de ce que Tu m'as appris, enseigne-moi ce qui me sera utile, et augmente-moi en savoir."), source: "Ibn Majah #252", occasions: ["knowledge"] },
  { catIdx: 10, title: loc("Du'a of Ibrahim", "Dua d'Ibrahim"), arabicText: "رَبِّ هَبْ لِي حُكْمًا وَأَلْحِقْنِي بِالصَّالِحِينَ، وَاجْعَل لِّي لِسَانَ صِدْقٍ فِي الْآخِرِينَ، وَاجْعَلنِي مِن وَرَثَةِ جَنَّةِ النَّعِيمِ", transliteration: "Rabbi habli hukman wa alhqni bis salihin, waj'al li lisana sidqin fil akhireen, waj'alni min warisati jannatin na'eem", translation: loc("My Lord, grant me wisdom and include me among the righteous, and give me a reputation of truth among the later generations, and make me of the inheritors of Paradise.", "Mon Seigneur, accorde-moi la sagesse et joins-moi aux vertueux, et donne-moi une réputation de vérité parmi les générations futures, et fais-moi héritier du Paradis."), source: "Quran 26:83-85", occasions: ["knowledge"] },

  // Category 12: For Health
  { catIdx: 11, title: loc("Du'a for Health", "Dua pour la santé"), arabicText: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ اشْفِهِ وَأَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ شِفَاءً لَا يُغَادِرُ سَقَمًا", transliteration: "Allahumma rabban nas adhhibil ba'sa ishfihi wa antash shafi la shifaa'a illa shifa'uka shifaan la yughadiru saqama", translation: loc("O Allah, Lord of mankind, remove the affliction and cure him, for You are the Curer. There is no cure except Your cure, a cure that leaves no illness.", "Ô Allah, Seigneur des hommes, éloigne l'affliction et guéris-le, car Tu es le Guérisseur. Il n'y a de guérison que Ta guérison, une guérison qui ne laisse aucune maladie."), source: "Bukhari #5750", occasions: ["health"] },
  { catIdx: 11, title: loc("Du'a for Wellbeing", "Dua pour le bien-être"), arabicText: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ", transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant", translation: loc("O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped except You.", "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nul n'a le droit d'être adoré excepté Toi."), source: "Abu Dawud #5089", occasions: ["health"] },
  { catIdx: 11, title: loc("Du'a when Ill", "Dua quand on est malade"), arabicText: "اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَأْسَ، وَاشْفِهِ، وَأَنْتَ الشَّافِي لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا", transliteration: "Allahumma rabban nas adhhibil ba'sa, ishfihi, wa antash shafi la shifaa'a illa shifa'uka, shifaan la yughadiru saqama", translation: loc("O Allah, Lord of mankind, remove the affliction and cure him. You are the Curer. There is no cure except Your cure, a cure that leaves no illness.", "Ô Allah, Seigneur des hommes, éloigne l'affliction et guéris-le. Tu es le Guérisseur. Il n'y a de guérison que Ta guérison, une guérison qui ne laisse aucune maladie."), source: "Bukhari #5750", occasions: ["health"] },
];

const AZKAR = [
  // Morning Adhkar
  { catIdx: 0, arabicText: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذَا الْيَوْمِ وَخَيْرَ مَا بَعْدَهُ، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذَا الْيَوْمِ وَشَرِّ مَا بَعْدَهُ، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ", transliteration: "Asbahna wa asbahal mulku lillah, wal hamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer, rabbi as'aluka khayra ma fi hadhal yawmi wa khayra ma ba'dahu, wa a'udhu bika min sharri ma fi hadhal yawmi wa sharri ma ba'dahu, rabbi a'udhu bika minal kasali wa su'il kibari, rabbi a'udhu bika min 'adhabin fin nari wa 'adhabin fil qabr", translation: loc("We enter the morning and all sovereignty belongs to Allah. Praise be to Allah. None has the right to be worshipped except Allah alone, with no partner. To Him belongs sovereignty and praise, and He has power over all things. My Lord, I ask You for the good of this day and the good of what follows it, and I seek refuge in You from the evil of this day and the evil of what follows it. My Lord, I seek refuge in You from laziness and the evil of old age. My Lord, I seek refuge in You from punishment in the Fire and punishment in the grave.", "Nous entrons dans la matinée et toute la souveraineté appartient à Allah. Louange à Allah. Nul n'a le droit d'être adoré excepté Allah seul, sans associé. À Lui la souveraineté et à Lui la louange, et Il a le pouvoir sur toute chose. Seigneur, je Te demande le bien de ce jour et le bien de ce qui suit, et je demande protection auprès de Toi contre le mal de ce jour et le mal de ce qui suit. Seigneur, je demande protection auprès de Toi contre la paresse et le mal de la vieillesse. Seigneur, je demande protection auprès de Toi contre le châtiment du Feu et le châtiment de la tombe."), source: "Muslim #2722", repeatCount: 1 },
  { catIdx: 0, arabicText: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ النُّشُورُ", transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu, wa ilaykin nushoor", translation: loc("O Allah, by You we enter the morning, and by You we enter the evening. By You we live, and by You we die, and to You is the resurrection.", "Ô Allah, par Toi nous entrons dans la matinée, et par Toi nous entrons dans la soirée. Par Toi nous vivons, et par Toi nous mourons, et vers Toi est la résurrection."), source: "Sunan at-Tirmidhi #5", repeatCount: 1 },
  { catIdx: 0, arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ", transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana 'ala ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bi ni'matika alayya, wa abu'u bi dhanbi faghfir li fa innahu la yaghfirudh dhunuba illa ant", translation: loc("O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant, and I keep to Your covenant and promise as best as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.", "Ô Allah, Tu es mon Seigneur. Nul n'a le droit d'être adoré excepté Toi. Tu m'as créé et je suis Ton serviteur, et je reste fidèle à Ton engagement et Ta promesse dans la mesure de mes capacités. Je demande protection auprès de Toi contre le mal de ce que j'ai fait. Je reconnais Ta faveur sur moi et je reconnais mon péché, alors pardonne-moi car nul ne pardonne les péchés si ce n'est Toi."), source: "Bukhari #6306 (Sayyid al-Istighfar)", repeatCount: 1 },
  { catIdx: 0, arabicText: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ", transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant", translation: loc("O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped except You.", "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nul n'a le droit d'être adoré excepté Toi."), source: "Abu Dawud #5089", repeatCount: 3 },
  { catIdx: 0, arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي", transliteration: "Allahumma inni as'alukal 'afiyyata fid dunya wal akhirah, Allahumma inni as'alukal 'afwa wal 'afiyyata fi deeni wa dunyaya wa ahli wa mali", translation: loc("O Allah, I ask You for well-being in this world and the Hereafter. O Allah, I ask You for pardon and well-being in my religion, my worldly life, my family, and my wealth.", "Ô Allah, je Te demande la santé dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et la santé dans ma religion, ma vie mondaine, ma famille et mes biens."), source: "Ibn Majah #3827", repeatCount: 1 },
  { catIdx: 0, arabicText: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", transliteration: "Hasbiyallahu la ilaha illa huwa, alayhi tawakkaltu wa huwa rabbul arshil adheem", translation: loc("Allah is sufficient for me. None has the right to be worshipped except Him. In Him I put my trust, and He is the Lord of the Magnificent Throne.", "Allah me suffit. Nul n'a le droit d'être adoré excepté Lui. En Lui je mets ma confiance, et Il est le Seigneur du Trône Magnifique."), source: "Abu Dawud #5081", repeatCount: 7 },
  { catIdx: 0, arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ، وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ", transliteration: "Allahumma inni a'udhu bika minal kufr, wal faqr, wa a'udhu bika min 'adhabil qabr", translation: loc("O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave.", "Ô Allah, je demande protection auprès de Toi contre l'incroyance et la pauvreté, et je demande protection auprès de Toi contre le châtiment de la tombe."), source: "Abu Dawud #5090", repeatCount: 3 },
  { catIdx: 0, arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ", transliteration: "Allahumma inni a'udhu bika minal hammi wal huzan, wa a'udhu bika minal ajzi wal kasal, wa a'udhu bika minal jubni wal bukhli, wa a'udhu bika ghalabatid dayni wa qahrir rijal", translation: loc("O Allah, I seek refuge in You from worry and grief, from helplessness and laziness, from cowardice and miserliness, and from being overcome by debt and being overpowered by people.", "Ô Allah, je demande protection auprès de Toi contre l'inquiétude et le chagrin, contre l'impuissance et la paresse, contre la lâcheté et l'avarice, et contre la domination des dettes et des hommes."), source: "Abu Dawud #5090", repeatCount: 3 },
  { catIdx: 0, arabicText: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahil ladhi la yadurru ma'asmihi shai'un fil ardi wa la fis sama'i, wa huwas samee'ul aleem", translation: loc("In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.", "Au nom d'Allah, avec le nom duquel rien sur terre ni dans les cieux ne peut nuire, et Il est l'Audient, l'Omniscient."), source: "Abu Dawud #5088", repeatCount: 3 },
  { catIdx: 0, arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ", transliteration: "Allahumma inni as'alukal jannata wa a'udhu bikan nar", translation: loc("O Allah, I ask You for Paradise and seek refuge in You from the Fire.", "Ô Allah, je Te demande le Paradis et je demande protection auprès de Toi contre le Feu."), source: "Abu Dawud #5089", repeatCount: 3 },

  // Evening Adhkar
  { catIdx: 1, arabicText: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ أَسْأَلُكَ خَيْرَ مَا فِي هَذِهِ اللَّيْلَةِ وَخَيْرَ مَا بَعْدَهَا، وَأَعُوذُ بِكَ مِنْ شَرِّ مَا فِي هَذِهِ اللَّيْلَةِ وَشَرِّ مَا بَعْدَهَا، رَبِّ أَعُوذُ بِكَ مِنَ الْكَسَلِ وَسُوءِ الْكِبَرِ، رَبِّ أَعُوذُ بِكَ مِنْ عَذَابٍ فِي النَّارِ وَعَذَابٍ فِي الْقَبْرِ", transliteration: "Amsayna wa amsal mulku lillah, wal hamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer, rabbi as'aluka khayra ma fi hadihil laylati wa khayra ma ba'daha, wa a'udhu bika min sharri ma fi hadihil laylati wa sharri ma ba'daha, rabbi a'udhu bika minal kasali wa su'il kibari, rabbi a'udhu bika min 'adhabin fin nari wa 'adhabin fil qabr", translation: loc("We enter the evening and all sovereignty belongs to Allah. Praise be to Allah. None has the right to be worshipped except Allah alone, with no partner. To Him belongs sovereignty and praise, and He has power over all things. My Lord, I ask You for the good of this night and the good of what follows it, and I seek refuge in You from the evil of this night and the evil of what follows it. My Lord, I seek refuge in You from laziness and the evil of old age. My Lord, I seek refuge in You from punishment in the Fire and punishment in the grave.", "Nous entrons dans la soirée et toute la souveraineté appartient à Allah. Louange à Allah. Nul n'a le droit d'être adoré excepté Allah seul, sans associé. À Lui la souveraineté et à Lui la louange, et Il a le pouvoir sur toute chose. Seigneur, je Te demande le bien de cette nuit et le bien de ce qui suit, et je demande protection auprès de Toi contre le mal de cette nuit et le mal de ce qui suit. Seigneur, je demande protection auprès de Toi contre la paresse et le mal de la vieillesse. Seigneur, je demande protection auprès de Toi contre le châtiment du Feu et le châtiment de la tombe."), source: "Muslim #2723", repeatCount: 1 },
  { catIdx: 1, arabicText: "اللَّهُمَّ بِكَ أَمْسَيْنَا، وَبِكَ أَصْبَحْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ، وَإِلَيْكَ الْمَصِيرُ", transliteration: "Allahumma bika amsayna, wa bika asbahna, wa bika nahya, wa bika namootu, wa ilaykal maseer", translation: loc("O Allah, by You we enter the evening, and by You we enter the morning. By You we live, and by You we die, and to You is our return.", "Ô Allah, par Toi nous entrons dans la soirée, et par Toi nous entrons dans la matinée. Par Toi nous vivons, et par Toi nous mourons, et vers Toi est notre retour."), source: "Sunan at-Tirmidhi #5", repeatCount: 1 },
  { catIdx: 1, arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ", transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana 'ala ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bi ni'matika alayya, wa abu'u bi dhanbi faghfir li fa innahu la yaghfirudh dhunuba illa ant", translation: loc("O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant, and I keep to Your covenant and promise as best as I can. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.", "Ô Allah, Tu es mon Seigneur. Nul n'a le droit d'être adoré excepté Toi. Tu m'as créé et je suis Ton serviteur, et je reste fidèle à Ton engagement et Ta promesse dans la mesure de mes capacités. Je demande protection auprès de Toi contre le mal de ce que j'ai fait. Je reconnais Ta faveur sur moi et je reconnais mon péché, alors pardonne-moi car nul ne pardonne les péchés si ce n'est Toi."), source: "Bukhari #6306", repeatCount: 1 },
  { catIdx: 1, arabicText: "بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ", transliteration: "Bismillahil ladhi la yadurru ma'asmihi shai'un fil ardi wa la fis sama'i, wa huwas samee'ul aleem", translation: loc("In the name of Allah, with whose name nothing on earth or in heaven can cause harm, and He is the All-Hearing, All-Knowing.", "Au nom d'Allah, avec le nom duquel rien sur terre ni dans les cieux ne peut nuire, et Il est l'Audient, l'Omniscient."), source: "Abu Dawud #5088", repeatCount: 3 },
  { catIdx: 1, arabicText: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي، لَا إِلَٰهَ إِلَّا أَنْتَ", transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari, la ilaha illa ant", translation: loc("O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight. None has the right to be worshipped except You.", "Ô Allah, accorde-moi la santé dans mon corps. Ô Allah, accorde-moi la santé dans mon ouïe. Ô Allah, accorde-moi la santé dans ma vue. Nul n'a le droit d'être adoré excepté Toi."), source: "Abu Dawud #5089", repeatCount: 3 },
  { catIdx: 1, arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ، اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي دِينِي وَدُنْيَايَ وَأَهْلِي وَمَالِي", transliteration: "Allahumma inni as'alukal 'afiyyata fid dunya wal akhirah, Allahumma inni as'alukal 'afwa wal 'afiyyata fi deeni wa dunyaya wa ahli wa mali", translation: loc("O Allah, I ask You for well-being in this world and the Hereafter. O Allah, I ask You for pardon and well-being in my religion, my worldly life, my family, and my wealth.", "Ô Allah, je Te demande la santé dans ce monde et dans l'au-delà. Ô Allah, je Te demande le pardon et la santé dans ma religion, ma vie mondaine, ma famille et mes biens."), source: "Ibn Majah #3827", repeatCount: 1 },
  { catIdx: 1, arabicText: "حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ", transliteration: "Hasbiyallahu la ilaha illa huwa, alayhi tawakkaltu wa huwa rabbul arshil adheem", translation: loc("Allah is sufficient for me. None has the right to be worshipped except Him. In Him I put my trust, and He is the Lord of the Magnificent Throne.", "Allah me suffit. Nul n'a le droit d'être adoré excepté Lui. En Lui je mets ma confiance, et Il est le Seigneur du Trône Magnifique."), source: "Abu Dawud #5081", repeatCount: 7 },
  { catIdx: 1, arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْكُفْرِ، وَالْفَقْرِ، وَأَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ", transliteration: "Allahumma inni a'udhu bika minal kufr, wal faqr, wa a'udhu bika min 'adhabil qabr", translation: loc("O Allah, I seek refuge in You from disbelief and poverty, and I seek refuge in You from the punishment of the grave.", "Ô Allah, je demande protection auprès de Toi contre l'incroyance et la pauvreté, et je demande protection auprès de Toi contre le châtiment de la tombe."), source: "Abu Dawud #5090", repeatCount: 3 },
  { catIdx: 1, arabicText: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ، وَأَعُوذُ بِكَ مِنَ الْجُبْنِ وَالْبُخْلِ، وَأَعُوذُ بِكَ مِنْ غَلَبَةِ الدَّيْنِ وَقَهْرِ الرِّجَالِ", transliteration: "Allahumma inni a'udhu bika minal hammi wal huzan, wa a'udhu bika minal ajzi wal kasal, wa a'udhu bika minal jubni wal bukhli, wa a'udhu bika ghalabatid dayni wa qahrir rijal", translation: loc("O Allah, I seek refuge in You from worry and grief, from helplessness and laziness, from cowardice and miserliness, and from being overcome by debt and being overpowered by people.", "Ô Allah, je demande protection auprès de Toi contre l'inquiétude et le chagrin, contre l'impuissance et la paresse, contre la lâcheté et l'avarice, et contre la domination des dettes et des hommes."), source: "Abu Dawud #5090", repeatCount: 3 },
  { catIdx: 1, arabicText: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ", transliteration: "Allahumma inni as'alukal jannata wa a'udhu bikan nar", translation: loc("O Allah, I ask You for Paradise and seek refuge in You from the Fire.", "Ô Allah, je Te demande le Paradis et je demande protection auprès de Toi contre le Feu."), source: "Abu Dawud #5089", repeatCount: 3 },

  // Before Sleep
  { catIdx: 2, arabicText: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا", transliteration: "Bismika Allahumma amootu wa ahya", translation: loc("In Your name, O Allah, I die and I live.", "En Ton nom, Ô Allah, je meurs et je vis."), source: "Bukhari #6324", repeatCount: 1 },
  { catIdx: 2, arabicText: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ", transliteration: "Allahumma qini 'adhabaka yawma tab'athu ibadak", translation: loc("O Allah, protect me from Your punishment on the Day You resurrect Your servants.", "Ô Allah, protège-moi de Ton châtiment le jour où Tu ressuscites Tes serviteurs."), source: "Abu Dawud #5089", repeatCount: 1 },
  { catIdx: 2, arabicText: "رَبِّ ادْخِلْنِي مُدْخَلَ صِدْقٍ، وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ، وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا", transliteration: "Rabbi udkhilni mudkhala sidqin, wa akhrijni mukhraja sidqin, waj'al li min ladunka sultanan naseera", translation: loc("My Lord, let me enter a sound entry and let me exit a sound exit, and grant me from Yourself a supporting authority.", "Mon Seigneur, fais-moi entrer d'une entrée honorable et sortir d'une sortie honorable, et accorde-moi de Ta part une autorité secourable."), source: "Quran 17:80", repeatCount: 1 },
  { catIdx: 2, arabicText: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَأَلْجَأْتُ ظَهْرِي إِلَيْكَ، رَغْبَةً وَرَهْبَةً إِلَيْكَ، لَا مَلْجَأَ وَلَا مَنْجَا مِنْكَ إِلَّا إِلَيْكَ، آمَنْتُ بِكِتَابِكَ الَّذِي أَنزَلْتَ وَبِنَبِيِّكَ الَّذِي أَرْسَلْتَ", transliteration: "Allahumma aslamtu nafsi ilayka, wa wajjahtu wajhi ilayka, wa fawwadtu amri ilayka, wa alja'tu zahri ilayka, raghbatan wa rahbatan ilayka, la malja'a wa la manja minka illa ilayka, amantu bi kitabikal ladhi anzalta wa bi nabiyyikal ladhi arsalt", translation: loc("O Allah, I submit myself to You, I direct my face to You, I entrust my affairs to You, and I seek Your protection, out of desire and fear of You. There is no refuge or escape from You except with You. I believe in Your Book which You have revealed and in Your Prophet whom You have sent.", "Ô Allah, je me soumets à Toi, je dirige mon visage vers Toi, je confie mes affaires à Toi, et je cherche Ta protection, par désir et par crainte de Toi. Il n'y a de refuge ni d'échappatoire de Toi qu'auprès de Toi. Je crois en Ton Livre que Tu as révélé et en Ton Prophète que Tu as envoyé."), source: "Bukhari #6317", repeatCount: 1 },
  { catIdx: 2, arabicText: "اللَّهُمَّ عَالِمَ الْغَيْبِ وَالشَّهَادَةِ، فَاطِرَ السَّمَاوَاتِ وَالْأَرْضِ، رَبَّ كُلِّ شَيْءٍ وَمَلِيكَهُ، أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا أَنْتَ، أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ الشَّيْطَانِ وَشِرْكِهِ", transliteration: "Allahumma 'alimal ghaybi wash shahadati, fatiras samawati wal ard, rabba kulli shay'in wa maleekahu, ashhadu an la ilaha illa ant, a'udhu bika min sharri nafsi, wa min sharrish shaytani wa shirkihi", translation: loc("O Allah, Knower of the unseen and the seen, Creator of the heavens and the earth, Lord of everything and its Master, I bear witness that none has the right to be worshipped except You. I seek refuge in You from the evil of my own self and from the evil of Shaytan and his shirk.", "Ô Allah, Connaître de l'invisible et du visible, Créateur des cieux et de la terre, Seigneur de toute chose et son Maître, j'atteste qu'il n'y a de dieu que Toi. Je demande protection auprès de Toi contre le mal de mon âme et contre le mal du Shaytan et son polythéisme."), source: "Tirmidhi #3388", repeatCount: 1 },
  { catIdx: 2, arabicText: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", transliteration: "Subhanallahi wa bihamdihi", translation: loc("Glorified is Allah and with His praise.", "Gloire à Allah et avec Sa louange."), source: "Muslim #2726", repeatCount: 100 },
  { catIdx: 2, arabicText: "آيَةُ الْكُرْسِيِّ", transliteration: "Ayat al-Kursi", translation: loc("The Verse of the Throne (Quran 2:255) — whoever recites it before sleeping, Allah will send a guardian angel to protect him.", "Le verset du Trône (Coran 2:255) — quiconque le récite avant de dormir, Allah enverra un ange gardien pour le protéger."), source: "Bukhari #2311", repeatCount: 1 },
  { catIdx: 2, arabicText: "قُلْ هُوَ اللَّهُ أَحَدٌ، اللَّهُ الصَّمَدُ، لَمْ يَلِدْ وَلَمْ يُولَدْ، وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ", transliteration: "Qul huwallahu ahad, Allahus samad, lam yalid wa lam yoolad, wa lam yakul lahoo kufuwan ahad", translation: loc("Surah Al-Ikhlas — whoever recites it three times before sleeping, Allah will suffice him.", "La sourate Al-Ikhlas — quiconque la récite trois fois avant de dormir, Allah lui suffira."), source: "Abu Dawud #5022", repeatCount: 3 },
  { catIdx: 2, arabicText: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ، مِنْ شَرِّ مَا خَلَقَ، وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ، وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ، وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ", transliteration: "Qul a'udhu bi rabbil falaq, min sharri ma khalaq, wa min sharri ghasiqin idha waqab, wa min sharrin naffathati fil uqad, wa min sharri hasidin idha hasad", translation: loc("Surah Al-Falaq — seeking refuge from evil.", "La sourate Al-Falaq — demande de refuge contre le mal."), source: "Abu Dawud #5022", repeatCount: 3 },
  { catIdx: 2, arabicText: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ، مَلِكِ النَّاسِ، إِلَٰهِ النَّاسِ، مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ، الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ، مِنَ الْجِنَّةِ وَالنَّاسِ", transliteration: "Qul a'udhu bi rabbinnas, malikinnas, ilahinnas, min sharril waswasil khannas, alladhi yuwaswisu fi sudoorinnas, minal jinnati wannas", translation: loc("Surah An-Nas — seeking refuge in the Lord of mankind from the whispering Shaytan.", "La sourate An-Nas — demande de refuge auprès du Seigneur des hommes contre le chuchotement du Shaytan."), source: "Abu Dawud #5022", repeatCount: 3 },

  // After Prayer
  { catIdx: 3, arabicText: "أَسْتَغْفِرُ اللَّهَ", transliteration: "Astaghfirullah", translation: loc("I seek forgiveness from Allah.", "Je demande pardon à Allah."), source: "Muslim #591", repeatCount: 3 },
  { catIdx: 3, arabicText: "اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Allahumma antas salamu wa minkas salam, tabarakta ya dhal jalali wal ikram", translation: loc("O Allah, You are Peace and from You comes peace. Blessed are You, O Possessor of majesty and honor.", "Ô Allah, Tu es la Paix et de Toi vient la Paix. Tu es béni, Ô Possesseur de majesté et d'honneur."), source: "Muslim #592", repeatCount: 1 },
  { catIdx: 3, arabicText: "سُبْحَانَ اللَّهِ، الْحَمْدُ لِلَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ، اللَّهُ أَكْبَرُ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ", transliteration: "Subhanallahi, wal hamdu lillahi, la ilaha illallahu, Allahu Akbar, la hawla wa la quwwata illa billah", translation: loc("Glorified is Allah. Praise be to Allah. None has the right to be worshipped except Allah. Allah is the Greatest. There is no power nor might except with Allah.", "Gloire à Allah. Louange à Allah. Nul n'a le droit d'être adoré excepté Allah. Allah est le Plus Grand. Il n'y a ni force ni puissance si ce n'est avec Allah."), source: "Muslim #593", repeatCount: 1 },
  { catIdx: 3, arabicText: "اللَّهُمَّ لَا مَانِعَ لِمَا أَعْطَيْتَ، وَلَا مُعْطِيَ لِمَا مَنَعْتَ، وَلَا يَنْفَعُ ذَا الْجَدِّ مِنْكَ الْجَدُّ", transliteration: "Allahumma la mani'a lima a'tayt, wa la mu'tiya lima mana't, wa la yanfa'u dhal jaddi minkal jadd", translation: loc("O Allah, none can withhold what You give, and none can give what You withhold, and no wealth or power can benefit anyone against You.", "Ô Allah, nul ne peut retenir ce que Tu donnes, et nul ne peut donner ce que Tu retiens, et aucune richesse ni puissance ne profite contre Toi."), source: "Bukhari #844", repeatCount: 1 },
  { catIdx: 3, arabicText: "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ، لَا إِلَٰهَ إِلَّا اللَّهُ، وَلَا نَعْبُدُ إِلَّا إِيَّاهُ، لَهُ النِّعْمَةُ وَلَهُ الْفَضْلُ وَلَهُ الثَّنَاءُ الْحَسَنُ، لَا إِلَٰهَ إِلَّا اللَّهُ مُخْلِصِينَ لَهُ الدِّينَ وَلَوْ كَرِهَ الْكَافِرُونَ", transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer, la hawla wa la quwwata illa billah, la ilaha illallahu, wa la na'budu illa iyyah, lahun ni'matu wa lahul fadlu wa lahuth thanaul hasan, la ilaha illallahu mukhliseena lahud deena walaw karihal kafirun", translation: loc("None has the right to be worshipped except Allah alone, with no partner. To Him belongs sovereignty and praise, and He has power over all things. There is no power nor might except with Allah. None has the right to be worshipped except Allah, and we worship none but Him. To Him belongs all bounty, all grace, and all excellent praise. None has the right to be worshipped except Allah, being sincere to Him in religion, even if the disbelievers hate it.", "Nul n'a le droit d'être adoré excepté Allah seul, sans associé. À Lui la souveraineté et à Lui la louange, et Il a le pouvoir sur toute chose. Il n'y a ni force ni puissance si ce n'est avec Allah. Nul n'a le droit d'être adoré excepté Allah, et nous n'adorons que Lui. À Lui toute bénédiction, toute grâce et toute louange excellente. Nul n'a le droit d'être adoré excepté Allah, en Lui vouant un culte exclusif, même si les mécréants le détestent."), source: "Muslim #594", repeatCount: 1 },

  // Istighfar
  { catIdx: 4, arabicText: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ", transliteration: "Astaghfirullaha wa atubu ilayhi", translation: loc("I seek forgiveness from Allah and repent to Him.", "Je demande pardon à Allah et me repens vers Lui."), source: "Bukhari #6307", repeatCount: 100 },
  { catIdx: 4, arabicText: "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَٰهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَىٰ عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ", transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana abduka, wa ana 'ala ahdika wa wa'dika mastata'tu, a'udhu bika min sharri ma sana'tu, abu'u laka bi ni'matika alayya, wa abu'u bi dhanbi faghfir li fa innahu la yaghfirudh dhunuba illa ant", translation: loc("O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant. I seek refuge in You from the evil of what I have done. I acknowledge Your favor upon me and I acknowledge my sin, so forgive me, for none forgives sins except You.", "Ô Allah, Tu es mon Seigneur. Nul n'a le droit d'être adoré excepté Toi. Tu m'as créé et je suis Ton serviteur. Je demande protection auprès de Toi contre le mal de ce que j'ai fait. Je reconnais Ta faveur sur moi et je reconnais mon péché, alors pardonne-moi car nul ne pardonne les péchés si ce n'est Toi."), source: "Bukhari #6306 (Sayyid al-Istighfar)", repeatCount: 1 },
  { catIdx: 4, arabicText: "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ", transliteration: "Rabbana zalamna anfusana wa illam taghfir lana wa tarhamna lanakunanna minal khasireen", translation: loc("Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.", "Notre Seigneur, nous avons fait du tort à nous-mêmes, et si Tu ne nous pardonne pas et n'as pas pitié de nous, nous serons certes parmi les perdants."), source: "Quran 7:23", repeatCount: 3 },
  { catIdx: 4, arabicText: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ", transliteration: "Rabbi-ghfir li wa tub 'alayya innaka antat tawwabur raheem", translation: loc("My Lord, forgive me and accept my repentance, for indeed You are the Accepting of Repentance, the Merciful.", "Mon Seigneur, pardonne-moi et accepte mon repentance, car Tu es certes l'Accepteur du repentir, le Miséricordieux."), source: "Quran 2:186", repeatCount: 3 },
  { catIdx: 4, arabicText: "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ", transliteration: "Subhanallahi wa bihamdihi, subhanallahil adheem", translation: loc("Glorified is Allah and with His praise. Glorified is Allah, the Almighty.", "Gloire à Allah et avec Sa louange. Gloire à Allah, le Tout-Puissant."), source: "Bukhari #7437", repeatCount: 100 },

  // Salawat on the Prophet
  { catIdx: 5, arabicText: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ، كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ، إِنَّكَ حَمِيدٌ مَجِيدٌ", transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammadin, kama sallaita 'ala Ibrahima wa 'ala ali Ibrahima, innaka hamidun majid, Allahumma barik 'ala Muhammadin wa 'ala ali Muhammadin, kama barakta 'ala Ibrahima wa 'ala ali Ibrahima, innaka hamidun majid", translation: loc("O Allah, send prayers upon Muhammad and the family of Muhammad, as You sent prayers upon Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious. O Allah, bless Muhammad and the family of Muhammad, as You blessed Ibrahim and the family of Ibrahim. Indeed, You are Praiseworthy and Glorious.", "Ô Allah, envoie des prières sur Muhammad et la famille de Muhammad, comme Tu as envoyé des prières sur Ibrahim et la famille d'Ibrahim. Certes, Tu es Digne de louange et Glorieux. Ô Allah, bénis Muhammad et la famille de Muhammad, comme Tu as béni Ibrahim et la famille d'Ibrahim. Certes, Tu es Digne de louange et Glorieux."), source: "Bukhari #3370", repeatCount: 10 },
  { catIdx: 5, arabicText: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ النَّبِيِّ وَعَلَى آلِهِ وَسَلِّمْ", transliteration: "Allahumma salli 'ala Muhammadin nabiyyin wa 'ala alihi wa sallim", translation: loc("O Allah, send prayers upon Muhammad the Prophet and upon his family and grant them peace.", "Ô Allah, envoie des prières sur Muhammad le Prophète et sur sa famille et accorde-leur la paix."), source: "Muslim #384", repeatCount: 10 },
  { catIdx: 5, arabicText: "اللَّهُمَّ صَلِّ وَسَلِّمْ وَبَارِكْ عَلَى سَيِّدِنَا مُحَمَّدٍ", transliteration: "Allahumma salli wa sallim wa barik 'ala sayyidina Muhammadin", translation: loc("O Allah, send prayers, peace, and blessings upon our master Muhammad.", "Ô Allah, envoie des prières, la paix et les bénédictions sur notre maître Muhammad."), source: "Darimi", repeatCount: 100 },
];

const SEED_META_KEY = "dua_azkar_seeded";

export const seedDuas = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db
      .query("duaCategories")
      .first();
    if (existing) return { seeded: false, message: "Data already seeded." };

    const catIds: string[] = [];
    for (const cat of DUA_CATEGORIES) {
      const id = await ctx.db.insert("duaCategories", {
        name: cat.name,
        description: cat.description,
        icon: cat.icon,
        sortOrder: cat.sortOrder,
      });
      catIds.push(id as string);
    }

    for (const dua of DUAS) {
      await ctx.db.insert("duas", {
        categoryId: catIds[dua.catIdx] as any,
        title: dua.title,
        arabicText: dua.arabicText,
        transliteration: dua.transliteration,
        translation: dua.translation,
        source: dua.source,
        occasions: dua.occasions,
      });
    }

    const azkarCatIds: string[] = [];
    for (const cat of AZKAR_CATEGORIES) {
      const id = await ctx.db.insert("azkarCategories", {
        name: cat.name,
        description: cat.description,
        type: cat.type,
        sortOrder: cat.sortOrder,
      });
      azkarCatIds.push(id as string);
    }

    for (const zikr of AZKAR) {
      await ctx.db.insert("azkar", {
        categoryId: azkarCatIds[zikr.catIdx] as any,
        arabicText: zikr.arabicText,
        transliteration: zikr.transliteration,
        translation: zikr.translation,
        repeatCount: zikr.repeatCount,
        source: zikr.source,
      });
    }

    return { seeded: true, message: `Seeded ${DUA_CATEGORIES.length} dua categories, ${DUAS.length} duas, ${AZKAR_CATEGORIES.length} azkar categories, ${AZKAR.length} azkar.` };
  },
});
