import React from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, useScroll, useTransform, useSpring } from 'framer-motion';
import { BookOpen, Headphones, Shield, Globe, Sparkles } from 'lucide-react';

const topics = [
  {
    icon: <BookOpen className="w-7 h-7 text-brand-600" />,
    title: "Verified Library",
    description: "Deep dive into thousands of scholarly documents and research papers, all verified for authenticity."
  },
  {
    icon: <Headphones className="w-7 h-7 text-brand-600" />,
    title: "Scholarly Podcasts",
    description: "Listen to profound discussions on theology and contemporary law with Islamic thinkers."
  },
  {
    icon: <Shield className="w-7 h-7 text-brand-600" />,
    title: "Council Guidance",
    description: "Nuanced, tradition-rooted guidance generated by our specialized multi-agent AI council."
  },
  {
    icon: <Globe className="w-7 h-7 text-brand-600" />,
    title: "Knowledge Circle",
    description: "A secure, global community dedicated to serious study and respectful, authentic inquiry."
  }
];

const FloatingIcon = ({ icon, delay = 0 }: { icon: React.ReactNode, delay?: number }) => {
  const { scrollYProgress } = useScroll();
  const y = useTransform(scrollYProgress, [0, 1], [0, -150 * (delay + 1)]);
  const rotate = useTransform(scrollYProgress, [0, 1], [0, 45 * (delay + 1)]);

  return (
    <motion.div 
      style={{ y, rotate }}
      className="absolute pointer-events-none opacity-[0.05] text-brand-600"
    >
      {icon}
    </motion.div>
  );
};

const TopicsSection = () => {
  const navigate = useNavigate();
  return (
    <section className="py-32 bg-premium-gray relative overflow-hidden">
      {/* Parallax Background Accents */}
      <FloatingIcon icon={<Sparkles className="w-48 h-48" />} delay={0.2} />
      <div className="absolute right-[-5%] top-[20%]"><FloatingIcon icon={<BookOpen className="w-64 h-64" />} delay={0.5} /></div>
      <div className="absolute left-[10%] bottom-[10%]"><FloatingIcon icon={<Shield className="w-40 h-40" />} delay={0.8} /></div>

      <div className="container mx-auto px-4 lg:px-8 relative z-10">
        <div className="flex flex-col lg:flex-row gap-20 lg:items-center">
          {/* Left Text Column */}
          <div className="lg:w-1/3">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-8"
            >
              <h3 className="text-[10px] font-black uppercase tracking-[0.5em] text-brand-600">The Discovery</h3>
              <h2 className="text-5xl md:text-6xl font-black text-slate-950 tracking-tighter leading-[0.9] mb-8">
                One Space to <br />
                <span className="text-slate-300">Grow.</span>
              </h2>
              <p className="text-xl text-slate-500 font-medium leading-relaxed">
                We've built more than a platform. It's a structured journey from curiosity to verified certainty.
              </p>
              
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => navigate('/login')}
                className="btn-saas-primary !px-10 !py-6"
              >
                Join the Journey
              </motion.button>
            </motion.div>
          </div>

          {/* Right 2x2 Interactive Grid */}
          <div className="lg:w-2/3 grid grid-cols-1 sm:grid-cols-2 gap-8">
            {topics.map((topic, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.9 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.8, delay: index * 0.1, ease: [0.16, 1, 0.3, 1] }}
                whileHover={{ y: -10, rotateZ: index % 2 === 0 ? 1 : -1 }}
                className="p-10 rounded-[3rem] border border-slate-100 bg-white shadow-sm hover:shadow-2xl hover:shadow-slate-200/50 hover:border-brand-200 transition-all duration-500 group"
              >
                <div className="w-16 h-16 rounded-[1.25rem] bg-slate-50 border border-slate-100 flex items-center justify-center mb-8 group-hover:scale-110 group-hover:bg-brand-50 transition-all">
                  {topic.icon}
                </div>
                <h4 className="text-2xl font-black text-slate-950 mb-4 tracking-tight">
                  {topic.title}
                </h4>
                <p className="text-slate-500 text-base leading-relaxed font-medium">
                  {topic.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default TopicsSection;
