import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/auth/AuthContext';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    'chat.placeholder': 'Ask me anything about Islam...',
    'chat.welcome': 'Asalamu alaikum, I am Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Get authentic Islamic answers from multiple scholarly perspectives.',
    'chat.thinking': 'Thinking...',
    'chat.error': 'Failed to get response. Please try again.',
    'chat.clear_history': 'Clear History',
    'chat.feature1.title': 'Multiple Perspectives',
    'chat.feature1.desc': 'Get answers from different Islamic schools of thought',
    'chat.feature2.title': 'Scholarly Sources',
    'chat.feature2.desc': 'Responses based on authentic Islamic sources',
    'chat.feature3.title': 'Contextual Answers',
    'chat.feature3.desc': 'Detailed explanations with proper context',
    'chat.council_consensus': 'Council Consensus',
    'chat.council_members': 'Members',
    'chat.council_reasoning': 'Reasoning',
    'status.online': 'Online',
    'chat.history_cleared': 'History Cleared',
    'chat.history_cleared_desc': 'Chat history has been cleared',
    'chat.invalid_response': 'Invalid response from server',
    // Council
    'council.no_members': 'No council members available',
    'council.model': 'Model',
    'council.creativity_level': 'Creativity Level',
    'council.consensus_analysis': 'Consensus Analysis',
    'council.consensus_score': 'Consensus Score',
    'council.processing_time': 'Processing Time',
    'council.confidence': 'Confidence',
    'council.ask_title': 'Ask the Council',
    'council.ask_placeholder': 'Ask a complex question and let the Council analyze it from multiple perspectives...',
    'council.deliberating': 'Council is Deliberating...',
    'council.ask_button': 'Ask Council',
    'council.upload.title': 'Title',
    'council.upload.title_placeholder': 'Document title',
    'council.upload.source': 'Source',
    'council.upload.source_placeholder': 'Document source (e.g., Islamic Text, Legal Document)',
    'council.upload.category': 'Category',
    'council.upload.content': 'Content',
    'council.upload.content_placeholder': 'Paste document content here',
    'council.upload.submit': 'Upload Document',
    'council.upload.uploading': 'Uploading...',
    'council.upload.category.general': 'General (All Agents)',
    'council.upload.category.fiqh': 'Fiqh Reasoning Agent',
    'council.upload.category.aqeedah': 'Aqeedah Boundary Agent',
    'council.upload.category.humility': 'Humility & Abstention Agent',
    'council.upload.category.context': 'Contemporary Context Agent',
    // Media
    'media.title': 'Media',
    'media.subtitle': 'Islamic Content Library',
    'media.intro': 'Discover Islamic content curated for all ages - videos, podcasts, and educational materials.',
    'media.loading': 'Loading videos...',
    'media.empty': 'No videos available yet.',
    'media.watch': 'Watch',
    'media.duration': 'Duration',
    // Events
    'events.title': 'Events',
    'events.subtitle': 'Community Events',
    'events.intro': 'Join lectures, workshops, and gatherings in your area.',
    'events.loading': 'Loading events...',
    'events.empty': 'No events scheduled yet.',
    'events.register': 'Register',
    'events.registered': 'Registered',
    'events.location': 'Location',
    'events.date': 'Date',
    'events.attendees': 'Attendees',
    'auth.required': 'Authentication Required',
    'auth.signin': 'Please sign in to ask questions',
    'nav.daily': 'Daily Islam',
    'nav.chat': 'Chat',
    'nav.videos': 'Videos',
    'nav.events': 'Events',
    'nav.library': 'Library',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.circle': 'Circle of Knowledge',
    'nav.documents': 'Documents',
    'nav.signout': 'Sign Out',
    'hero.title_1': 'Your Digital',
    'hero.users': 'Trusted by 10,000+ Muslims',
    'hero.rating': '4.9/5 Rating',
    'hero.cta_primary': 'Get Started',
    'hero.cta_secondary': 'Learn More',
    'nav.signin': 'Sign In',
    'nav.rag_test': 'RAG Test',
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pricing': 'Pricing',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.learn': 'Learn',
    'nav.podcasts': 'Podcasts',
    'nav.community': 'Community',
    'nav.ai_companion': 'AI Companion',
    'index.learn_more': 'Learn More',
    // Library
    'library.title': 'Digital Islamic Library',
    'library.subtitle': 'Access a comprehensive collection of Islamic books, texts, and resources',
    'library.search_placeholder': 'Search books by title, author, or topic...',
    'library.filter_category': 'Category',
    'library.filter_language': 'Language',
    'library.filter_format': 'Format',
    'library.all_categories': 'All Categories',
    'library.all_languages': 'All Languages',
    'library.all_formats': 'All Formats',
    'library.downloads': 'downloads',
    'library.pages': 'pages',
    'library.file_size': 'MB',
    'library.download_button': 'Download',
    'library.featured': 'Featured',
    'library.no_results': 'No books found matching your criteria',
    'library.categories.quran': 'Quran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqeedah',
    'library.categories.seerah': 'Seerah',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Arabic Learning',
    'library.categories.dua': 'Dua & Dhikr',
    'library.categories.general': 'General',
    'library.languages.ar': 'Arabic',
    'library.languages.en': 'English',
    'library.languages.fr': 'French',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.cta_primary': 'Try it free',
    'hero.cta_secondary': 'How it works',
    // Footer
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    // 404
    'notfound.message': 'The page you are looking for does not exist or has been moved.',
    'notfound.return_home': 'Return Home',
    // Index (Landing)
    'index.features_title': 'What you get',
    'index.features_subtitle': 'Islamic guidance, daily content, and a full library — all in one place.',
    'index.guided_fatwa_title': 'Ask a Question',
    'index.guided_fatwa_desc': "Get a structured fatwa with the ruling, evidence, and explanation — checked across four madhhabs.",
    'index.try_it_now': 'Try it',
    'index.daily_islam_title': 'Daily Reminders',
    'index.daily_islam_desc': "A daily ayah, hadith, and dua. Plus a weekly quiz to keep your knowledge sharp.",
    'index.see_today': "See today's",
    'index.library_title': 'Islamic Library',
    'index.library_desc': 'Books, PDFs, and resources on Fiqh, Aqeedah, Seerah, and more.',
    'index.browse_books': 'Browse',
    'index.how_title_prefix': 'How it works',
    'index.how_subtitle': 'Every answer follows a structured process rooted in authentic sources.',
    'index.step1_title': 'Pick your madhhab',
    'index.step1_desc': "Choose Hanafi, Maliki, Shafi'i, or Hanbali. Answers are grounded in that tradition.",
    'index.step2_title': 'Built for Senegal',
    'index.step2_desc': 'Understands local customs and the realities of Muslim life in West Africa.',
    'index.step3_title': 'Referenced answers',
    'index.step3_desc': "Every fatwa includes clear references from Qur'an, Hadith, and classical texts.",
    'index.step4_title': 'Islamic topics only',
    'index.step4_desc': 'The AI stays focused on Islamic guidance and politely declines off-topic questions.',
    'index.final_cta_title': 'Ready to ask your first question?',
    'index.final_cta_desc': 'Start a fatwa session or explore the daily content. Free to try, no credit card needed.',
    'index.ask_question_btn': 'Get started',
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to access your account.',
    'login.create_account_title': 'Create an Account',
    'login.create_account_subtitle': 'Enter your details to get started.',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot your password?',
    'login.processing': 'Processing...',
    'login.sign_in': 'Sign In',
    'login.sign_up': 'Sign Up',
    'login.full_name': 'Full Name',
    'login.full_name_required': 'Full name is required',
    'common.success': 'Success',
    'common.error': 'Error',
    'login.success_signed_in': 'You have been logged in successfully!',
    'login.success_signed_up': 'Your account has been created successfully!',
    'login.failed': 'Login failed',
    'login.failed_desc': 'Could not sign in',
    'login.no_account': "Don't have an account?",
    'login.already_account': "Already have an account?",
    'login.back_to_login': "Back to login",
    'login.reset_desc': "Enter your email to receive reset instructions",
    'login.send_reset_link': "Send Reset Link",
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.return_home': 'Return to Home',
    // Dashboard
    'dashboard.todays_reminder': 'Today\'s Reminder',
    'dashboard.todays_prayer_times': 'Today\'s Prayer Times',
    'dashboard.todays_action': 'Today\'s Action',
    'dashboard.hadith_of_the_day': 'Hadith of the Day',
    'dashboard.source_authentic_hadith': 'Source: Authentic Hadith',
    'dashboard.prayer_times': 'Prayer Times',
    'dashboard.enable_location': 'Enable location to see prayer times',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Take a moment to reflect on today\'s ayah. Recite it in your prayers and contemplate its meaning throughout the day.',
    'dashboard.hadith_text': 'The Prophet (peace be upon him) said: \'The best of people are those who are most beneficial to people.\'',
    'dashboard.sectionLabel': 'Today\'s Islamic Knowledge',
    'dashboard.titlePrefix': 'Your personalized',
    'dashboard.titleHighlight': 'daily content',
    'dashboard.intro': 'Verses, duÊ¿as, small facts, and weekly quizzes â€“ to reconnect with Allah every day.',
    'dashboard.ayahOfTheDay': 'Verse of the Day',
    'dashboard.loading': 'Loadingâ€¦',
    'dashboard.ayahLoading': 'Loading today\'s verseâ€¦',
    'dashboard.ayahError': 'Could not load today\'s verse.',
    'dashboard.todayLabel': 'Today',
    'dashboard.todaySummary': 'Today: one verse, one hadith, one duÊ¿a, and a small action you can do.',
    'dashboard.openReminder': 'Open today\'s reminder',
    'dashboard.dailyDua': 'Today\'s DuÊ¿a',
    'dashboard.dailyDuaLoading': 'Loading today\'s duÊ¿aâ€¦',
    'dashboard.dailyDuaError': 'Could not load today\'s duÊ¿a.',
    'dashboard.smallFact': 'Small Fact',
    'dashboard.factLoading': 'Loading today\'s factâ€¦',
    'dashboard.factError': 'Could not load today\'s fact.',
    'dashboard.weeklyQuiz': 'Weekly Quiz',
    'dashboard.weeklyQuizSubtitle': 'One question, three levels.',
    'dashboard.easy': 'Easy',
    'dashboard.medium': 'Medium',
    'dashboard.advanced': 'Advanced',
    'dashboard.checkAnswer': 'Check Answer',
    'dashboard.correctFeedback': 'MashaAllah! Correct answer.',
    'dashboard.wrongFeedbackPrefix': 'Hint: ',
    // Quiz (Easy)
    'quiz.easy.question': "How many daily obligatory prayers are there in Islam?",
    'quiz.easy.options.0': "Three",
    'quiz.easy.options.1': "Five",
    'quiz.easy.options.2': "Seven",
    'quiz.easy.correct': "Five",
    'quiz.easy.hint': "Think of Fajr, Dhuhr, Ê¿Asr, Maghrib, Ê¿IshÄÊ¾.",
    // Quiz (Medium)
    'quiz.medium.question': "In Maliki fiqh, what is one key condition for following an imÄm in congregational prayer?",
    'quiz.medium.options.0': "Standing directly in front of the imÄm",
    'quiz.medium.options.1': "Intending to follow the imÄm at the beginning of the prayer",
    'quiz.medium.options.2': "Reciting SÅ«rat al-FÄtiá¸¥ah aloud with the imÄm",
    'quiz.medium.correct': "Intending to follow the imÄm at the beginning of the prayer",
    'quiz.medium.hint': "It relates to your niyyah (intention).",
    // Quiz (Advanced)
    'quiz.advanced.question': "According to many Maliki jurists, when can local custom (Ê¿urf) be used in rulings?",
    'quiz.advanced.options.0': "Whenever it is popular, even if it contradicts QurÊ¾Än and Sunnah",
    'quiz.advanced.options.1': "When it does not oppose clear textual evidence and helps clarify contracts or practices",
    'quiz.advanced.options.2': "Only in matters of pure worship (Ê¿ibÄdÄt)",
    'quiz.advanced.correct': "When it does not oppose clear textual evidence and helps clarify contracts or practices",
    'quiz.advanced.hint': "Custom cannot override explicit texts.",
    // Admin
    'admin.select_category': 'Select category',
    'admin.select_language': 'Select language',
    'admin.select_format': 'Select format',
    'admin.publisher_name': 'Publisher name',
    // Errors
    'error.registration_failed': 'Registration failed',
    'error.checkout_failed': 'Checkout failed',
    'error.search_failed': 'Search failed',
    'error.upload_failed': 'Upload failed',
    'error.delete_failed': 'Could not delete document.',
    'error.delete_document': 'Delete document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Select a Surah',
    'tarteel.loading_surah': 'Loading Surah...',
    'tarteel.listening_title': 'Listening...',
    'tarteel.listening_desc': 'Please recite the highlighted verse.',
    'tarteel.mic_error_title': 'Microphone Error',
    'tarteel.mic_error_desc': 'Could not access microphone. Please ensure permissions are granted.',
    'tarteel.file_too_large_title': 'File Too Large',
    'tarteel.file_too_large_desc': 'Recording exceeds the 10MB limit. Please try a shorter recitation.',
    'tarteel.success_title': 'MashaAllah!',
    'tarteel.success_desc': 'Your recitation was correct.',
    'tarteel.correction_title': 'Correction Needed',
    'tarteel.heard_label': 'We heard:',
    'tarteel.api_error_title': 'Analysis Error',
    'tarteel.api_error_desc': 'Could not process your recitation. Please try again.',
    'tarteel.tap_mic': 'Tap microphone to start reciting',
    'tarteel.overlay_analyzing': 'Analyzing Recitation...',
    'tarteel.overlay_checking': 'Checking pronunciation, tajweed, and memorization accuracy.',
    'tarteel.ayah_label': 'Ayah',
    // Pricing
    'pricing.title_prefix': 'Choose Your',
    'pricing.subtitle': 'Start free, upgrade when you need more. All plans include authentic Islamic knowledge.',
    'pricing.tier.free.name': 'Free',
    'pricing.tier.free.description': 'Discovery and first exposure to the system',
    'pricing.tier.core.name': 'Core',
    'pricing.tier.core.description': 'The main experience for most users',
    'pricing.tier.pro.name': 'Pro',
    'pricing.tier.pro.description': 'For serious, long-term users',
    'pricing.most_popular': 'MOST POPULAR',
    'pricing.upgrade_prefix': 'Upgrade to',
    'pricing.get_started_free': 'Get Started Free',
    'pricing.per_month': '/month',
    'pricing.feature.chat_credits': '{count} chat credits/month',
    'pricing.feature.unlimited_credits': 'Unlimited chat credits',
    'pricing.feature.basic_responses': 'Basic AI responses',
    'pricing.feature.standard_time': 'Standard response time',
    'pricing.feature.specialized_modes': 'Specialized modes',
    'pricing.feature.personalized_themes': 'Personalized themes',
    'pricing.feature.full_customization': 'Full theme customization',
    'pricing.feature.memory': 'Memory & context',
    'pricing.feature.advanced_memory': 'Advanced memory',
    'pricing.feature.templates': 'Templates',
    'pricing.feature.all_templates': 'All templates',
    'pricing.feature.priority': 'Priority responses',
    'pricing.feature.advanced_planning': 'Advanced planning',
    'pricing.feature.early_access': 'Early access to features',
    'pricing.feature.all_modes': 'All specialized modes',
    'pricing.footer_note': 'All plans include access to Quran study tools, Fatwa requests, and Islamic guidance.'
  },
  fr: {
    'chat.placeholder': 'Demandez-moi quoi que ce soit sur l\'Islam...',
    'chat.welcome': 'Asalamu alaikum, je suis Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Obtenez des rÃ©ponses islamiques authentiques de multiples perspectives savantes.',
    'chat.thinking': 'RÃ©flexion...',
    'chat.error': 'Ã‰chec de la rÃ©ponse. Veuillez rÃ©essayer.',
    'chat.history_cleared': 'Historique effacÃ©',
    'chat.history_cleared_desc': 'L\'historique du chat a Ã©tÃ© effacÃ©',
    'chat.invalid_response': 'RÃ©ponse invalide du serveur',
    'chat.clear_history': 'Effacer l\'historique',
    'chat.feature1.title': 'Perspectives multiples',
    'chat.feature1.desc': 'Obtenez des rÃ©ponses de diffÃ©rentes Ã©coles de pensÃ©e islamiques',
    'chat.feature2.title': 'Sources savantes',
    'chat.feature2.desc': 'RÃ©ponses basÃ©es sur des sources islamiques authentiques',
    'chat.feature3.title': 'RÃ©ponses contextuelles',
    'chat.feature3.desc': 'Explications dÃ©taillÃ©es avec le contexte appropriÃ©',
    'chat.council_consensus': 'Consensus du Conseil',
    'chat.council_members': 'Membres',
    'chat.council_reasoning': 'Raisonnement',
    'status.online': 'En ligne',
    // Council
    'council.no_members': 'Aucun membre du conseil disponible',
    'council.model': 'ModÃ¨le',
    'council.creativity_level': 'Niveau de CrÃ©ativitÃ©',
    'council.consensus_analysis': 'Analyse de Consensus',
    'council.consensus_score': 'Score de Consensus',
    'council.processing_time': 'Temps de Traitement',
    'council.confidence': 'Confiance',
    'council.ask_title': 'Demander au Conseil',
    'council.ask_placeholder': 'Posez une question complexe et laissez le Conseil l\'analyser sous plusieurs perspectives...',
    'council.deliberating': 'Le Conseil dÃ©libÃ¨re...',
    'council.ask_button': 'Demander au Conseil',
    'council.upload.title': 'Titre',
    'council.upload.title_placeholder': 'Titre du document',
    'council.upload.source': 'Source',
    'council.upload.source_placeholder': 'Source du document (ex: Texte Islamique, Document Juridique)',
    'council.upload.category': 'CatÃ©gorie',
    'council.upload.content': 'Contenu',
    'council.upload.content_placeholder': 'Collez le contenu du document ici',
    'council.upload.submit': 'TÃ©lÃ©charger le Document',
    'council.upload.uploading': 'TÃ©lÃ©chargement...',
    'council.upload.category.general': 'GÃ©nÃ©ral (Tous les Agents)',
    'council.upload.category.fiqh': 'Agent de Raisonnement Fiqh',
    'council.upload.category.aqeedah': 'Agent de Limite Aqida',
    'council.upload.category.humility': 'Agent d\'HumilitÃ© & Abstention',
    'council.upload.category.context': 'Agent de Contexte Contemporain',
    // Media
    'media.title': 'MÃ©dia',
    'media.subtitle': 'BibliothÃ¨que de contenu islamique',
    'media.intro': 'DÃ©couvrez du contenu islamique sÃ©lectionnÃ© pour tous les Ã¢ges - vidÃ©os, podcasts et matÃ©riels Ã©ducatifs.',
    'media.loading': 'Chargement des vidÃ©os...',
    'media.empty': 'Aucune vidÃ©o disponible pour le moment.',
    'media.watch': 'Regarder',
    'media.duration': 'DurÃ©e',
    // Events
    'events.title': 'Ã‰vÃ©nements',
    'events.subtitle': 'Ã‰vÃ©nements communautaires',
    'events.intro': 'Rejoignez des confÃ©rences, ateliers et rassemblements dans votre rÃ©gion.',
    'events.loading': 'Chargement des Ã©vÃ©nements...',
    'events.empty': 'Aucun Ã©vÃ©nement programmÃ© pour le moment.',
    'events.register': 'S\'inscrire',
    'events.registered': 'Inscrit',
    'events.location': 'Lieu',
    'events.date': 'Date',
    'events.attendees': 'Participants',
    'auth.required': 'Authentification Requise',
    'auth.signin': 'Veuillez vous connecter pour poser des questions',
    'nav.daily': 'Islam Quotidien',
    'nav.chat': 'Chat',
    'nav.videos': 'VidÃ©os',
    'nav.events': 'Ã‰vÃ©nements',
    'nav.library': 'BibliothÃ¨que',
    'nav.settings': 'ParamÃ¨tres',
    'nav.admin': 'Admin',
    'nav.circle': 'Cercle de Savoir',
    'nav.documents': 'Documents',
    'nav.signout': 'DÃ©connexion',
    'hero.title_1': 'Votre Compagnon',
    'hero.users': 'Approuvé par 10 000+ Musulmans',
    'hero.rating': 'Note 4.9/5',
    'hero.cta_primary': 'Commencer',
    'hero.cta_secondary': 'En Savoir Plus',
    'nav.signin': 'Connexion',
    'nav.rag_test': 'Test RAG',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.pricing': 'Tarifs',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.learn': 'Apprendre',
    'nav.podcasts': 'Podcasts',
    'nav.community': 'Communauté',
    'nav.ai_companion': 'Compagnon IA',
    'index.learn_more': 'En savoir plus',
    // Library
    'library.title': 'BibliothÃ¨que NumÃ©rique Islamique',
    'library.subtitle': 'AccÃ©dez Ã  une collection complÃ¨te de livres, textes et ressources islamiques',
    'library.search_placeholder': 'Rechercher par titre, auteur ou sujet...',
    'library.filter_category': 'CatÃ©gorie',
    'library.filter_language': 'Langue',
    'library.filter_format': 'Format',
    'library.all_categories': 'Toutes les catÃ©gories',
    'library.all_languages': 'Toutes les langues',
    'library.all_formats': 'Tous les formats',
    'library.downloads': 'tÃ©lÃ©chargements',
    'library.pages': 'pages',
    'library.file_size': 'Mo',
    'library.download_button': 'TÃ©lÃ©charger',
    'library.featured': 'En vedette',
    'library.no_results': 'Aucun livre trouvÃ© correspondant Ã  vos critÃ¨res',
    'library.categories.quran': 'Coran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqida',
    'library.categories.seerah': 'Sira',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Apprentissage de l\'Arabe',
    'library.categories.dua': 'Dou\'a & Dhikr',
    'library.categories.general': 'GÃ©nÃ©ral',
    'library.languages.ar': 'Arabe',
    'library.languages.en': 'Anglais',
    'library.languages.fr': 'FranÃ§ais',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    // Footer
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    // 404
    'notfound.message': "La page que vous recherchez n'existe pas ou a été déplacée.",
    'notfound.return_home': "Retour à l'accueil",
    // Hero
    'hero.cta_primary': 'Essayer gratuitement',
    'hero.cta_secondary': 'Comment ça marche',
    // Index
    'index.features_title': 'Ce que vous obtenez',
    'index.features_subtitle': 'Guidance islamique, contenu quotidien et bibliothèque — tout en un.',
    'index.guided_fatwa_title': 'Poser une question',
    'index.guided_fatwa_desc': "Obtenez une fatwa structurée avec le hukm, les preuves et l'explication — vérifiée sur quatre madhhabs.",
    'index.try_it_now': 'Essayer',
    'index.daily_islam_title': 'Rappels quotidiens',
    'index.daily_islam_desc': "Un verset, un hadith et une dou'a chaque jour. Plus un quiz hebdomadaire.",
    'index.see_today': "Voir aujourd'hui",
    'index.library_title': 'Bibliothèque islamique',
    'index.library_desc': 'Livres, PDF et ressources sur le Fiqh, la Aqeedah, la Seerah et plus.',
    'index.browse_books': 'Parcourir',
    'index.how_title_prefix': 'Comment ça marche',
    'index.how_subtitle': "Chaque réponse suit un processus structuré basé sur des sources authentiques.",
    'index.step1_title': 'Choisissez votre madhhab',
    'index.step1_desc': "Hanafi, Maliki, Shafi'i ou Hanbali. Les réponses sont ancrées dans cette tradition.",
    'index.step2_title': 'Conçu pour le Sénégal',
    'index.step2_desc': "Comprend les coutumes locales et la réalité de la vie musulmane en Afrique de l'Ouest.",
    'index.step3_title': 'Réponses référencées',
    'index.step3_desc': "Chaque fatwa inclut des références claires au Coran, aux Hadiths et aux textes classiques.",
    'index.step4_title': 'Sujets islamiques uniquement',
    'index.step4_desc': "L'IA reste focalisée sur l'orientation islamique et décline poliment les questions hors sujet.",
    'index.final_cta_title': 'Prêt à poser votre première question ?',
    'index.final_cta_desc': "Lancez une session de fatwa ou explorez le contenu quotidien. Gratuit, sans carte bancaire.",
    'index.ask_question_btn': 'Commencer',
    // Login
    'login.title': 'Bon retour',
    'login.subtitle': 'Connectez-vous pour accÃ©der Ã  votre compte.',
    'login.create_account_title': 'CrÃ©er un compte',
    'login.create_account_subtitle': 'Entrez vos informations pour commencer.',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.remember_me': 'Se souvenir de moi',
    'login.forgot_password': 'Mot de passe oubliÃ© ?',
    'login.processing': 'Traitement...',
    'login.sign_in': 'Connexion',
    'login.sign_up': 'Inscription',
    'login.full_name': 'Nom complet',
    'login.full_name_required': 'Le nom complet est requis',
    'common.success': 'SuccÃ¨s',
    'common.error': 'Erreur',
    'login.success_signed_in': 'Vous Ãªtes connectÃ© avec succÃ¨s !',
    'login.success_signed_up': 'Votre compte a Ã©tÃ© crÃ©Ã© avec succÃ¨s !',
    'login.failed': 'Ã‰chec de la connexion',
    'login.failed_desc': 'Impossible de se connecter',
    'login.no_account': "Vous n'avez pas de compte ?",
    'login.already_account': "Vous avez déjà un compte ?",
    'login.back_to_login': "Retour à la connexion",
    'login.reset_desc': "Entrez votre email pour recevoir les instructions de réinitialisation",
    'login.send_reset_link': "Envoyer le lien de réinitialisation",
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oups ! Page introuvable',
    'notfound.return_home': "Retour Ã  l'accueil",
    // Dashboard
    'dashboard.todays_reminder': 'Rappel du jour',
    'dashboard.todays_prayer_times': 'Heures de priÃ¨re du jour',
    'dashboard.todays_action': 'Action du jour',
    'dashboard.hadith_of_the_day': 'Hadith du jour',
    'dashboard.source_authentic_hadith': 'Source : Hadith authentique',
    'dashboard.prayer_times': 'Heures de priÃ¨re',
    'dashboard.enable_location': 'Activez la localisation pour voir les heures de priÃ¨re',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Prenez un moment pour rÃ©flÃ©chir Ã  l\'ayah du jour. RÃ©citez-la dans vos priÃ¨res et mÃ©ditez sur sa signification tout au long de la journÃ©e.',
    'dashboard.hadith_text': 'Le ProphÃ¨te (paix sur lui) a dit : \'Les meilleurs des gens sont ceux qui sont les plus bÃ©nÃ©fiques aux gens.\'',
    'dashboard.sectionLabel': 'Savoir Islamique du Jour',
    'dashboard.titlePrefix': 'Votre contenu',
    'dashboard.titleHighlight': 'quotidien personnalisÃ©',
    'dashboard.intro': 'Versets, duÊ¿as, petits faits et quiz hebdomadaires â€“ pour renouer avec Allah chaque jour.',
    'dashboard.ayahOfTheDay': 'Verset du Jour',
    'dashboard.loading': 'Chargementâ€¦',
    'dashboard.ayahLoading': 'Chargement du verset du jourâ€¦',
    'dashboard.ayahError': 'Impossible de charger le verset du jour.',
    'dashboard.todayLabel': 'Aujourd\'hui',
    'dashboard.todaySummary': 'Aujourd\'hui : un verset, un hadith, une duÊ¿a, et une petite action que vous pouvez faire.',
    'dashboard.openReminder': 'Ouvrir le rappel du jour',
    'dashboard.dailyDua': 'DuÊ¿a du Jour',
    'dashboard.dailyDuaLoading': 'Chargement de la duÊ¿a du jourâ€¦',
    'dashboard.dailyDuaError': 'Impossible de charger la duÊ¿a du jour.',
    'dashboard.smallFact': 'Petit Fait',
    'dashboard.factLoading': 'Chargement du fait du jourâ€¦',
    'dashboard.factError': 'Impossible de charger le fait du jour.',
    'dashboard.weeklyQuiz': 'Quiz Hebdomadaire',
    'dashboard.weeklyQuizSubtitle': 'Une question, trois niveaux.',
    'dashboard.easy': 'Facile',
    'dashboard.medium': 'Moyen',
    'dashboard.advanced': 'AvancÃ©',
    'dashboard.checkAnswer': 'VÃ©rifier la RÃ©ponse',
    'dashboard.correctFeedback': 'MashaAllah ! Bonne rÃ©ponse.',
    'dashboard.wrongFeedbackPrefix': 'Indice : ',
    // Quiz (Easy)
    'quiz.easy.question': "Combien de priÃ¨res obligatoires quotidiennes y a-t-il en Islam ?",
    'quiz.easy.options.0': "Trois",
    'quiz.easy.options.1': "Cinq",
    'quiz.easy.options.2': "Sept",
    'quiz.easy.correct': "Cinq",
    'quiz.easy.hint': "Pense Ã  Fajr, Dhuhr, Ê¿Asr, Maghrib, Ê¿IshÄÊ¾.",
    // Quiz (Medium)
    'quiz.medium.question': "En fiqh malikite, quelle est une condition clÃ© pour suivre lâ€™imam en priÃ¨re collective ?",
    'quiz.medium.options.0': "Se tenir directement devant lâ€™imam",
    'quiz.medium.options.1': "Avoir lâ€™intention de suivre lâ€™imam au dÃ©but de la priÃ¨re",
    'quiz.medium.options.2': "RÃ©citer la FÄtiá¸¥a Ã  voix haute avec lâ€™imam",
    'quiz.medium.correct': "Avoir lâ€™intention de suivre lâ€™imam au dÃ©but de la priÃ¨re",
    'quiz.medium.hint': "Cela concerne la niyyah (intention).",
    // Quiz (Advanced)
    'quiz.advanced.question': "Selon de nombreux juristes malikites, quand peut-on utiliser la coutume locale (Ê¿urf) dans les rÃ¨gles ?",
    'quiz.advanced.options.0': "Chaque fois quâ€™elle est populaire, mÃªme si elle contredit le Coran et la Sunna",
    'quiz.advanced.options.1': "Lorsquâ€™elle nâ€™oppose pas un texte clair et aide Ã  clarifier des contrats ou pratiques",
    'quiz.advanced.options.2': "Uniquement dans les questions dâ€™adoration (Ê¿ibÄdÄt)",
    'quiz.advanced.correct': "Lorsquâ€™elle nâ€™oppose pas un texte clair et aide Ã  clarifier des contrats ou pratiques",
    'quiz.advanced.hint': "La coutume ne peut pas contredire des textes explicites.",
    // Admin
    'admin.select_category': 'SÃ©lectionner la catÃ©gorie',
    'admin.select_language': 'SÃ©lectionner la langue',
    'admin.select_format': 'SÃ©lectionner le format',
    'admin.publisher_name': 'Nom de l\'Ã©diteur',
    // Errors
    'error.registration_failed': 'Ã‰chec de l\'inscription',
    'error.checkout_failed': 'Ã‰chec du paiement',
    'error.search_failed': 'Ã‰chec de la recherche',
    'error.upload_failed': 'Ã‰chec du tÃ©lÃ©chargement',
    'error.delete_failed': 'Impossible de supprimer le document.',
    'error.delete_document': 'Supprimer le document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'SÃ©lectionner une sourate',
    'tarteel.loading_surah': 'Chargement de la sourate...',
    'tarteel.listening_title': 'Ã‰coute en cours...',
    'tarteel.listening_desc': 'Veuillez rÃ©citer le verset en surbrillance.',
    'tarteel.mic_error_title': 'Erreur de microphone',
    'tarteel.mic_error_desc': 'Impossible dâ€™accÃ©der au microphone. VÃ©rifiez les permissions.',
    'tarteel.file_too_large_title': 'Fichier trop volumineux',
    'tarteel.file_too_large_desc': 'Lâ€™enregistrement dÃ©passe 10 Mo. Essayez une rÃ©citation plus courte.',
    'tarteel.success_title': 'MashaAllah !',
    'tarteel.success_desc': 'Votre rÃ©citation est correcte.',
    'tarteel.correction_title': 'Correction nÃ©cessaire',
    'tarteel.heard_label': 'Nous avons entendu :',
    'tarteel.api_error_title': 'Erreur dâ€™analyse',
    'tarteel.api_error_desc': 'Impossible de traiter votre rÃ©citation. Veuillez rÃ©essayer.',
    'tarteel.tap_mic': 'Appuyez sur le micro pour commencer',
    'tarteel.overlay_analyzing': 'Analyse de la rÃ©citation...',
    'tarteel.overlay_checking': 'VÃ©rification de la prononciation, du tajwid et de la mÃ©morisation.',
    'tarteel.ayah_label': 'Verset',
    // Pricing
    'pricing.title_prefix': 'Choisissez Votre',
    'pricing.subtitle': 'Commencez gratuitement, mettez Ã  niveau quand vous avez besoin de plus. Tous les plans incluent un savoir islamique authentique.',
    'pricing.tier.free.name': 'Gratuit',
    'pricing.tier.free.description': 'DÃ©couverte et premiÃ¨re exposition au systÃ¨me',
    'pricing.tier.core.name': 'Core',
    'pricing.tier.core.description': 'L\'expÃ©rience principale pour la plupart des utilisateurs',
    'pricing.tier.pro.name': 'Pro',
    'pricing.tier.pro.description': 'Pour les utilisateurs sÃ©rieux Ã  long terme',
    'pricing.most_popular': 'LE PLUS POPULAIRE',
    'pricing.upgrade_prefix': 'Passer Ã ',
    'pricing.get_started_free': 'Commencer Gratuitement',
    'pricing.per_month': '/mois',
    'pricing.feature.chat_credits': '{count} crÃ©dits chat/mois',
    'pricing.feature.unlimited_credits': 'CrÃ©dits chat illimitÃ©s',
    'pricing.feature.basic_responses': 'RÃ©ponses IA basiques',
    'pricing.feature.standard_time': 'Temps de rÃ©ponse standard',
    'pricing.feature.specialized_modes': 'Modes spÃ©cialisÃ©s',
    'pricing.feature.personalized_themes': 'ThÃ¨mes personnalisÃ©s',
    'pricing.feature.full_customization': 'Personnalisation complÃ¨te du thÃ¨me',
    'pricing.feature.memory': 'MÃ©moire et contexte',
    'pricing.feature.advanced_memory': 'MÃ©moire avancÃ©e',
    'pricing.feature.templates': 'ModÃ¨les',
    'pricing.feature.all_templates': 'Tous les modÃ¨les',
    'pricing.feature.priority': 'RÃ©ponses prioritaires',
    'pricing.feature.advanced_planning': 'Planification avancÃ©e',
    'pricing.feature.early_access': 'AccÃ¨s anticipÃ© aux fonctionnalitÃ©s',
    'pricing.feature.all_modes': 'Tous les modes spÃ©cialisÃ©s',
    'pricing.footer_note': 'Tous les plans incluent l\'accÃ¨s aux outils d\'Ã©tude du Coran, aux demandes de fatwa et aux conseils islamiques.'
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();

  const readStored = (): Language => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('GëstuSaDine-language') as Language;
      if (saved && ['en', 'fr'].includes(saved)) return saved;
    }
    // Firebase User doesn't have user_metadata on the client object directly
    // would need to fetch from Firestore profile
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(readStored);

  // Sync document lang and persist
  useEffect(() => {
    document.documentElement.lang = language;
    if (typeof window !== 'undefined') {
      localStorage.setItem('GëstuSaDine-language', language);
    }
    if (user) {
      // Profile updates are now handled via Firestore in AuthContext or Profile settings
    }
  }, [language, user]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const current = (translations as Record<string, Record<string, string>>)[language];
    const translate = (dict?: Record<string, string>) => {
      const value = dict?.[key];
      if (!value) return undefined;
      if (!params) return value;
      return Object.keys(params).reduce((acc, paramKey) => {
        const token = `{${paramKey}}`;
        return acc.replace(token, String(params[paramKey]));
      }, value);
    };

    const currentValue = translate(current);
    if (currentValue) return currentValue;

    const fallback = (translations as Record<string, Record<string, string>>).en;
    const fallbackValue = translate(fallback);
    if (fallbackValue) return fallbackValue;
    if (import.meta.env.DEV) {
      console.warn(`Missing translation key: ${key} for ${language}`);
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
