import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/auth/AuthContext';
import { supabase } from '@/lib/supabase';

type Language = 'en' | 'fr' | 'wo';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    'chat.placeholder': 'Ask me anything about Islam...',
    'chat.welcome': 'Asalamu alaikum, I am Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Get authentic Islamic answers from multiple scholarly perspectives.',
    'chat.thinking': 'Thinking...',
    'chat.error': 'Failed to get response. Please try again.',
    'chat.clear_history': 'Clear History',
    'chat.feature1.title': 'Multiple Perspectives',
    'chat.feature1.desc': 'Get answers from different Islamic schools of thought',
    'chat.feature2.title': 'Scholarly Sources',
    'chat.feature2.desc': 'Responses based on authentic Islamic sources',
    'chat.feature3.title': 'Contextual Answers',
    'chat.feature3.desc': 'Detailed explanations with proper context',
    'chat.council_consensus': 'Council Consensus',
    'chat.council_members': 'Members',
    'chat.council_reasoning': 'Reasoning',
    'status.online': 'Online',
    // Media
    'media.title': 'Media',
    'media.subtitle': 'Islamic Content Library',
    'media.intro': 'Discover Islamic content curated for all ages - videos, podcasts, and educational materials.',
    'media.loading': 'Loading videos...',
    'media.empty': 'No videos available yet.',
    'media.watch': 'Watch',
    'media.duration': 'Duration',
    // Events
    'events.title': 'Events',
    'events.subtitle': 'Community Events',
    'events.intro': 'Join lectures, workshops, and gatherings in your area.',
    'events.loading': 'Loading events...',
    'events.empty': 'No events scheduled yet.',
    'events.register': 'Register',
    'events.registered': 'Registered',
    'events.location': 'Location',
    'events.date': 'Date',
    'events.attendees': 'Attendees',
    // Shop
    'shop.title': 'Shop',
    'shop.shop_label': 'Shop',
    'shop.islamic': 'Islamic',
    'shop.store': 'Store',
    'shop.browse_desc': 'Browse and purchase Islamic products, books, and merchandise',
    'shop.waitlist_title': 'Merch previews. Join the preorder list.',
    'shop.waitlist_subtitle': 'Exclusive drops, limited runs, and intentional designs. No payments yet—reserve your spot and be notified first.',
    'shop.waitlist_exclusive': 'Exclusive early access',
    'shop.waitlist_drop_hint': 'Drops announced in waves',
    'shop.preview': 'Preview',
    'shop.preorder': 'Preorder spot',
    'shop.waitlist_description': 'Join the list to get notified when this drop opens.',
    'shop.waitlist_price_hint': 'Expected from {price} {currency}',
    'shop.waitlist_email_placeholder': 'Email for early access',
    'shop.waitlist_cta': 'Notify me first',
    'shop.waitlist_joined_short': 'You are on the list',
    'shop.waitlist_joined': 'You’re on the preorder list. We will notify you first.',
    'shop.waitlist_invalid_email': 'Enter a valid email to join.',
    'shop.order_created': 'Order created! Redirecting to payment...',
    'shop.updated_qty': 'Updated quantity in cart',
    'shop.added_to_cart': 'Added to cart',
    'shop.removed_from_cart': 'Item removed from cart',
    'shop.subtitle': 'Islamic Products',
    'shop.intro': 'Discover modest clothing, books, accessories, and resources to deepen your Islamic knowledge.',
    'shop.loading': 'Loading products...',
    'shop.empty': 'No products available yet.',
    'shop.add_to_cart': 'Add to Cart',
    'shop.checkout': 'Checkout',
    'shop.price': 'Price',
    'shop.in_stock': 'In Stock',
    'shop.out_of_stock': 'Out of Stock',
    'shop.category': 'Category',
    'shop.sort_by': 'Sort by',
    'shop.all': 'All',
    'shop.default': 'Default',
    'shop.price_low': 'Price: Low to High',
    'shop.price_high': 'Price: High to Low',
    'shop.name': 'Name',
    'shop.shopping_cart': 'Shopping Cart',
    'shop.cart_empty': 'Your cart is empty',
    'shop.items_in_cart': 'item',
    'shop.items_in_cart_plural': 'items',
    'shop.in_your_cart': 'in your cart',
    'shop.size': 'Size',
    'shop.total': 'Total',
    'shop.proceed_checkout': 'Proceed to Checkout',
    'shop.drop': 'Drop',
    'shop.drag_to_cart': '← Drag to cart',
    'shop.select_size_drag': 'Select size to drag',
    'shop.limited': 'Limited',
    'auth.required': 'Authentication Required',
    'auth.signin': 'Please sign in to ask questions',
    'nav.daily': 'Daily Islam',
    'nav.chat': 'Chat',
    'nav.videos': 'Videos',
    'nav.events': 'Events',
    'nav.shop': 'Shop',
    'nav.library': 'Library',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.circle': 'Circle of Knowledge',
    'nav.documents': 'Documents',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.home': 'Home',
    // Library
    'library.title': 'Digital Islamic Library',
    'library.subtitle': 'Access a comprehensive collection of Islamic books, texts, and resources',
    'library.search_placeholder': 'Search books by title, author, or topic...',
    'library.filter_category': 'Category',
    'library.filter_language': 'Language',
    'library.filter_format': 'Format',
    'library.all_categories': 'All Categories',
    'library.all_languages': 'All Languages',
    'library.all_formats': 'All Formats',
    'library.downloads': 'downloads',
    'library.pages': 'pages',
    'library.file_size': 'MB',
    'library.download_button': 'Download',
    'library.featured': 'Featured',
    'library.no_results': 'No books found matching your criteria',
    'library.categories.quran': 'Quran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqeedah',
    'library.categories.seerah': 'Seerah',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Arabic Learning',
    'library.categories.dua': 'Dua & Dhikr',
    'library.categories.general': 'General',
    'library.languages.ar': 'Arabic',
    'library.languages.en': 'English',
    'library.languages.fr': 'French',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Islamic Knowledge\nAt Your Fingertips',
    'hero.subtitle': 'Your complete Islamic platform: scholarly guidance, daily inspiration, digital library, products, events, and media.',
    'hero.popular': 'Popular:',
    'hero.ask_now': 'Ask Now',
    // Footer
    'footer.contact': 'Contact Us',
    'footer.description': 'A platform dedicated to providing authentic Islamic knowledge through expert scholars.',
    'footer.rights': 'All Rights Reserved.',
    // Index (Landing)
    'index.what_title_prefix': 'An AI advisor for',
    'index.what_title_gradient': 'Islamic guidance',
    'index.what_subtitle': 'XamSaDine uses AI backed by expert scholars to provide structured, authentic answers to your questions about Islam.',
    'index.guided_fatwa_title': 'Guided Fatwa',
    'index.guided_fatwa_desc': "Ask any Islamic question and receive a structured answer with clarification, hukm, evidence, explanation, and advice.",
    'index.try_it_now': 'Try it now',
    'index.daily_islam_title': 'Daily Islam',
    'index.daily_islam_desc': "Start each day with an ayah, hadith, dua, a small fact, and a weekly quiz to keep your knowledge fresh.",
    'index.see_today': 'See today',
    'index.fiqh_map_title': 'Fiqh Map',
    'index.fiqh_map_desc': 'Explore fiqh themes across all four madhabs: worship, transactions, family, ethics, and local contexts.',
    'index.explore': 'Explore',
    'index.how_title_prefix': 'Built for',
    'index.how_title_gradient': 'Senegal and the Ummah',
    'index.how_subtitle': 'Every answer follows a calm, structured flow rooted in authentic sources.',
    'index.step1_title': 'Your madhab, your answers',
    'index.step1_desc': "Choose your school of fiqh (Hanafi, Maliki, Shafi'i, Hanbali) and receive answers grounded in that tradition.",
    'index.step2_title': 'Senegalese context',
    'index.step2_desc': 'XamSaDine understands local customs, language (Wolof, French), and the realities of Muslim life in Senegal.',
    'index.step3_title': 'Structured & authenticated',
    'index.step3_desc': "Each fatwa flows through 5 steps with clear references from Qur'an, Hadith, and classical texts of your madhab.",
    'index.step4_title': 'Islamic questions only',
    'index.step4_desc': 'XamSaDine is dedicated to Islamic guidance. It gently declines non-Islamic topics to stay focused.',
    'index.final_cta_title': 'Ready to ask your first question?',
    'index.final_cta_desc': "Start a guided fatwa session or explore today's daily content. XamSaDine is here to walk with you.",
    'index.ask_question_btn': 'Ask a question',
    'index.see_daily_btn': 'See Daily Islam',
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to access your account.',
    'login.create_account_title': 'Create an Account',
    'login.create_account_subtitle': 'Enter your details to get started.',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot your password?',
    'login.processing': 'Processing...',
    'login.sign_in': 'Sign In',
    'login.sign_up': 'Sign Up',
    'login.full_name': 'Full Name',
    'login.full_name_required': 'Full name is required',
    'common.success': 'Success',
    'common.error': 'Error',
    'login.success_signed_in': 'You have been logged in successfully!',
    'login.success_signed_up': 'Your account has been created successfully!',
    'login.failed': 'Login failed',
    'login.failed_desc': 'Could not sign in',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.return_home': 'Return to Home',
    // Dashboard
    'dashboard.todays_reminder': 'Today\'s Reminder',
    'dashboard.todays_prayer_times': 'Today\'s Prayer Times',
    'dashboard.todays_action': 'Today\'s Action',
    'dashboard.hadith_of_the_day': 'Hadith of the Day',
    'dashboard.source_authentic_hadith': 'Source: Authentic Hadith',
    'dashboard.prayer_times': 'Prayer Times',
    'dashboard.enable_location': 'Enable location to see prayer times',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Take a moment to reflect on today\'s ayah. Recite it in your prayers and contemplate its meaning throughout the day.',
    'dashboard.hadith_text': 'The Prophet (peace be upon him) said: \'The best of people are those who are most beneficial to people.\'',
    // Admin
    'admin.select_category': 'Select category',
    'admin.select_language': 'Select language',
    'admin.select_format': 'Select format',
    'admin.publisher_name': 'Publisher name',
    // Errors
    'error.registration_failed': 'Registration failed',
    'error.checkout_failed': 'Checkout failed',
    'error.search_failed': 'Search failed',
    'error.upload_failed': 'Upload failed',
    'error.delete_failed': 'Could not delete document.',
    'error.delete_document': 'Delete document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Select a Surah',
    'tarteel.loading_surah': 'Loading Surah...',
    'tarteel.listening_title': 'Listening...',
    'tarteel.listening_desc': 'Please recite the highlighted verse.',
    'tarteel.mic_error_title': 'Microphone Error',
    'tarteel.mic_error_desc': 'Could not access microphone. Please ensure permissions are granted.',
    'tarteel.file_too_large_title': 'File Too Large',
    'tarteel.file_too_large_desc': 'Recording exceeds the 10MB limit. Please try a shorter recitation.',
    'tarteel.success_title': 'MashaAllah!',
    'tarteel.success_desc': 'Your recitation was correct.',
    'tarteel.correction_title': 'Correction Needed',
    'tarteel.heard_label': 'We heard:',
    'tarteel.api_error_title': 'Analysis Error',
    'tarteel.api_error_desc': 'Could not process your recitation. Please try again.',
    'tarteel.tap_mic': 'Tap microphone to start reciting',
    'tarteel.overlay_analyzing': 'Analyzing Recitation...',
    'tarteel.overlay_checking': 'Checking pronunciation, tajweed, and memorization accuracy.',
    'tarteel.ayah_label': 'Ayah'
  },
  fr: {
    'chat.placeholder': 'Demandez-moi quoi que ce soit sur l\'Islam...',
    'chat.welcome': 'Asalamu alaikum, je suis Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Obtenez des réponses islamiques authentiques de multiples perspectives savantes.',
    'chat.thinking': 'Réflexion...',
    'chat.error': 'Échec de la réponse. Veuillez réessayer.',
    'chat.history_cleared': 'Historique effacé',
    'chat.history_cleared_desc': 'L\'historique du chat a été effacé',
    'chat.invalid_response': 'Réponse invalide du serveur',
    'chat.clear_history': 'Effacer l\'historique',
    'chat.feature1.title': 'Perspectives multiples',
    'chat.feature1.desc': 'Obtenez des réponses de différentes écoles de pensée islamiques',
    'chat.feature2.title': 'Sources savantes',
    'chat.feature2.desc': 'Réponses basées sur des sources islamiques authentiques',
    'chat.feature3.title': 'Réponses contextuelles',
    'chat.feature3.desc': 'Explications détaillées avec le contexte approprié',
    'chat.council_consensus': 'Consensus du Conseil',
    'chat.council_members': 'Membres',
    'chat.council_reasoning': 'Raisonnement',
    'status.online': 'En ligne',
    // Media
    'media.title': 'Média',
    'media.subtitle': 'Bibliothèque de contenu islamique',
    'media.intro': 'Découvrez du contenu islamique sélectionné pour tous les âges - vidéos, podcasts et matériels éducatifs.',
    'media.loading': 'Chargement des vidéos...',
    'media.empty': 'Aucune vidéo disponible pour le moment.',
    'media.watch': 'Regarder',
    'media.duration': 'Durée',
    // Events
    'events.title': 'Événements',
    'events.subtitle': 'Événements communautaires',
    'events.intro': 'Rejoignez des conférences, ateliers et rassemblements dans votre région.',
    'events.loading': 'Chargement des événements...',
    'events.empty': 'Aucun événement programmé pour le moment.',
    'events.register': 'S\'inscrire',
    'events.registered': 'Inscrit',
    'events.location': 'Lieu',
    'events.date': 'Date',
    'events.attendees': 'Participants',
    // Shop
    'shop.title': 'Boutique',
    'shop.shop_label': 'Boutique',
    'shop.islamic': 'Islamique',
    'shop.store': 'Magasin',
    'shop.browse_desc': 'Parcourez et achetez des produits islamiques, des livres et des marchandises',
    'shop.waitlist_title': 'Aperçus merch. Rejoignez la précommande.',
    'shop.waitlist_subtitle': 'Drops exclusifs, séries limitées, designs soignés. Pas de paiement maintenant—réservez votre place et soyez prévenu en premier.',
    'shop.waitlist_exclusive': 'Accès anticipé exclusif',
    'shop.waitlist_drop_hint': 'Les sorties arrivent par vagues',
    'shop.preview': 'Aperçu',
    'shop.preorder': 'Précommande',
    'shop.waitlist_description': 'Inscrivez-vous pour être prévenu dès que ce drop ouvre.',
    'shop.waitlist_price_hint': 'Prévu à partir de {price} {currency}',
    'shop.waitlist_email_placeholder': 'Email pour accès prioritaire',
    'shop.waitlist_cta': 'Prévenez-moi',
    'shop.waitlist_joined_short': 'Vous êtes sur la liste',
    'shop.waitlist_joined': 'Vous êtes sur la liste de précommande. Nous vous préviendrons en premier.',
    'shop.waitlist_invalid_email': 'Saisissez un email valide pour rejoindre la liste.',
    'shop.order_created': 'Commande créée ! Redirection vers le paiement...',
    'shop.updated_qty': 'Quantité mise à jour dans le panier',
    'shop.added_to_cart': 'Ajouté au panier',
    'shop.removed_from_cart': 'Article retiré du panier',
    'shop.subtitle': 'Produits islamiques',
    'shop.intro': 'Découvrez des vêtements modestes, livres, accessoires et ressources pour approfondir vos connaissances islamiques.',
    'shop.loading': 'Chargement des produits...',
    'shop.empty': 'Aucun produit disponible pour le moment.',
    'shop.add_to_cart': 'Ajouter au panier',
    'shop.checkout': 'Commander',
    'shop.price': 'Prix',
    'shop.in_stock': 'En stock',
    'shop.out_of_stock': 'Rupture de stock',
    'shop.category': 'Catégorie',
    'shop.sort_by': 'Trier par',
    'shop.all': 'Tout',
    'shop.default': 'Par défaut',
    'shop.price_low': 'Prix: Croissant',
    'shop.price_high': 'Prix: Décroissant',
    'shop.name': 'Nom',
    'shop.shopping_cart': 'Panier',
    'shop.cart_empty': 'Votre panier est vide',
    'shop.items_in_cart': 'article',
    'shop.items_in_cart_plural': 'articles',
    'shop.in_your_cart': 'dans votre panier',
    'shop.size': 'Taille',
    'shop.total': 'Total',
    'shop.proceed_checkout': 'Passer à la caisse',
    'shop.drop': 'Déposer',
    'shop.drag_to_cart': '← Glisser vers le panier',
    'shop.select_size_drag': 'Sélectionnez une taille pour glisser',
    'shop.limited': 'Limité',
    'auth.required': 'Authentification Requise',
    'auth.signin': 'Veuillez vous connecter pour poser des questions',
    'nav.daily': 'Islam Quotidien',
    'nav.chat': 'Chat',
    'nav.videos': 'Vidéos',
    'nav.events': 'Événements',
    'nav.shop': 'Boutique',
    'nav.library': 'Bibliothèque',
    'nav.settings': 'Paramètres',
    'nav.admin': 'Admin',
    'nav.circle': 'Cercle de Savoir',
    'nav.documents': 'Documents',
    'nav.signout': 'Déconnexion',
    'nav.signin': 'Connexion',
    'nav.home': 'Accueil',
    // Library
    'library.title': 'Bibliothèque Numérique Islamique',
    'library.subtitle': 'Accédez à une collection complète de livres, textes et ressources islamiques',
    'library.search_placeholder': 'Rechercher par titre, auteur ou sujet...',
    'library.filter_category': 'Catégorie',
    'library.filter_language': 'Langue',
    'library.filter_format': 'Format',
    'library.all_categories': 'Toutes les catégories',
    'library.all_languages': 'Toutes les langues',
    'library.all_formats': 'Tous les formats',
    'library.downloads': 'téléchargements',
    'library.pages': 'pages',
    'library.file_size': 'Mo',
    'library.download_button': 'Télécharger',
    'library.featured': 'En vedette',
    'library.no_results': 'Aucun livre trouvé correspondant à vos critères',
    'library.categories.quran': 'Coran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqida',
    'library.categories.seerah': 'Sira',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Apprentissage de l\'Arabe',
    'library.categories.dua': 'Dou\'a & Dhikr',
    'library.categories.general': 'Général',
    'library.languages.ar': 'Arabe',
    'library.languages.en': 'Anglais',
    'library.languages.fr': 'Français',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Connaissance Islamique\nÀ Portée de Main',
    'hero.subtitle': 'Votre plateforme islamique complète : conseils savants, inspiration quotidienne, bibliothèque numérique, produits, événements et médias.',
    'hero.popular': 'Populaire :',
    'hero.ask_now': 'Poser maintenant',
    // Footer
    'footer.contact': 'Contactez-nous',
    'footer.description': 'Une plateforme dédiée à fournir un savoir islamique authentique à travers des savants experts.',
    'footer.rights': 'Tous droits réservés.',
    // Index
    'index.what_title_prefix': 'Un conseiller IA pour',
    'index.what_title_gradient': "l'orientation islamique",
    'index.what_subtitle': "XamSaDine utilise l'IA, soutenue par des savants, pour fournir des réponses authentiques et structurées à vos questions sur l'Islam.",
    'index.guided_fatwa_title': 'Fatwa guidée',
    'index.guided_fatwa_desc': "Posez toute question islamique et recevez une réponse structurée avec clarification, hukm, preuves, explication et conseils.",
    'index.try_it_now': 'Essayez maintenant',
    'index.daily_islam_title': 'Islam quotidien',
    'index.daily_islam_desc': "Commencez chaque jour avec un verset, un hadith, une dou'a, un petit fait, et un quiz hebdomadaire pour entretenir votre savoir.",
    'index.see_today': "Voir aujourd'hui",
    'index.fiqh_map_title': 'Carte du fiqh',
    'index.fiqh_map_desc': "Explorez les thèmes du fiqh à travers les quatre madhabs : adoration, transactions, famille, éthique, et contextes locaux.",
    'index.explore': 'Explorer',
    'index.library_title': 'Bibliothèque Numérique',
    'index.library_desc': 'Accédez à des livres islamiques, des PDF et des ressources éducatives',
    'index.browse_books': 'Parcourir les livres',
    'index.how_title_prefix': 'Conçu pour',
    'index.how_title_gradient': "le Sénégal et l'Oumma",
    'index.how_subtitle': "Chaque réponse suit un flux calme et structuré, ancré dans des sources authentiques.",
    'index.step1_title': 'Votre madhab, vos réponses',
    'index.step1_desc': "Choisissez votre école de fiqh (hanafi, maliki, shafi'i, hanbali) et recevez des réponses adaptées à cette tradition.",
    'index.step2_title': 'Contexte sénégalais',
    'index.step2_desc': "XamSaDine comprend les coutumes locales, la langue (wolof, français) et la réalité de la vie musulmane au Sénégal.",
    'index.step3_title': 'Structuré et authentifié',
    'index.step3_desc': "Chaque fatwa suit 5 étapes avec des références claires au Coran, à la Sunna et aux textes classiques de votre madhab.",
    'index.step4_title': 'Questions islamiques uniquement',
    'index.step4_desc': "XamSaDine est dédié à l'orientation islamique et décline les sujets non islamiques pour rester focalisé.",
    'index.final_cta_title': 'Prêt à poser votre première question ?',
    'index.final_cta_desc': "Lancez une session de fatwa guidée ou explorez le contenu quotidien d'aujourd'hui. XamSaDine vous accompagne.",
    'index.ask_question_btn': 'Poser une question',
    'index.see_daily_btn': 'Voir Islam quotidien',
    // Login
    'login.title': 'Bon retour',
    'login.subtitle': 'Connectez-vous pour accéder à votre compte.',
    'login.create_account_title': 'Créer un compte',
    'login.create_account_subtitle': 'Entrez vos informations pour commencer.',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.remember_me': 'Se souvenir de moi',
    'login.forgot_password': 'Mot de passe oublié ?',
    'login.processing': 'Traitement...',
    'login.sign_in': 'Connexion',
    'login.sign_up': 'Inscription',
    'login.full_name': 'Nom complet',
    'login.full_name_required': 'Le nom complet est requis',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'login.success_signed_in': 'Vous êtes connecté avec succès !',
    'login.success_signed_up': 'Votre compte a été créé avec succès !',
    'login.failed': 'Échec de la connexion',
    'login.failed_desc': 'Impossible de se connecter',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oups ! Page introuvable',
    'notfound.return_home': "Retour à l'accueil",
    // Dashboard
    'dashboard.todays_reminder': 'Rappel du jour',
    'dashboard.todays_prayer_times': 'Heures de prière du jour',
    'dashboard.todays_action': 'Action du jour',
    'dashboard.hadith_of_the_day': 'Hadith du jour',
    'dashboard.source_authentic_hadith': 'Source : Hadith authentique',
    'dashboard.prayer_times': 'Heures de prière',
    'dashboard.enable_location': 'Activez la localisation pour voir les heures de prière',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Prenez un moment pour réfléchir à l\'ayah du jour. Récitez-la dans vos prières et méditez sur sa signification tout au long de la journée.',
    'dashboard.hadith_text': 'Le Prophète (paix sur lui) a dit : \'Les meilleurs des gens sont ceux qui sont les plus bénéfiques aux gens.\'',
    // Admin
    'admin.select_category': 'Sélectionner la catégorie',
    'admin.select_language': 'Sélectionner la langue',
    'admin.select_format': 'Sélectionner le format',
    'admin.publisher_name': 'Nom de l\'éditeur',
    // Errors
    'error.registration_failed': 'Échec de l\'inscription',
    'error.checkout_failed': 'Échec du paiement',
    'error.search_failed': 'Échec de la recherche',
    'error.upload_failed': 'Échec du téléchargement',
    'error.delete_failed': 'Impossible de supprimer le document.',
    'error.delete_document': 'Supprimer le document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Sélectionner une sourate',
    'tarteel.loading_surah': 'Chargement de la sourate...',
    'tarteel.listening_title': 'Écoute en cours...',
    'tarteel.listening_desc': 'Veuillez réciter le verset en surbrillance.',
    'tarteel.mic_error_title': 'Erreur de microphone',
    'tarteel.mic_error_desc': 'Impossible d’accéder au microphone. Vérifiez les permissions.',
    'tarteel.file_too_large_title': 'Fichier trop volumineux',
    'tarteel.file_too_large_desc': 'L’enregistrement dépasse 10 Mo. Essayez une récitation plus courte.',
    'tarteel.success_title': 'MashaAllah !',
    'tarteel.success_desc': 'Votre récitation est correcte.',
    'tarteel.correction_title': 'Correction nécessaire',
    'tarteel.heard_label': 'Nous avons entendu :',
    'tarteel.api_error_title': 'Erreur d’analyse',
    'tarteel.api_error_desc': 'Impossible de traiter votre récitation. Veuillez réessayer.',
    'tarteel.tap_mic': 'Appuyez sur le micro pour commencer',
    'tarteel.overlay_analyzing': 'Analyse de la récitation...',
    'tarteel.overlay_checking': 'Vérification de la prononciation, du tajwid et de la mémorisation.',
    'tarteel.ayah_label': 'Verset'
  },
  wo: {
    'chat.placeholder': 'Nan ma wax lé l\'Islaam...',
    'chat.welcome': 'Asalamu alaikum, man Anisah la',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Wañ japp ndax mi jëmm ju Iislaam ji yore wax yu bari xam-xam.',
    'chat.thinking': 'Mi nangu tànn...',
    'chat.error': 'Wula ju topp. Jàppleen ndax.',
    'chat.clear_history': 'Séetal jëfandikukat',
    'chat.feature1.title': 'Xalaat yu bari',
    'chat.feature1.desc': 'Jot tontu ci seetaan yu bari yu Islam',
    'chat.feature2.title': 'Jëmm yu xam-xam',
    'chat.feature2.desc': 'Tontu yu nëbb ci jëmm yu dëggu yu Islam',
    'chat.feature3.title': 'Tontu yu kontekst',
    'chat.feature3.desc': 'Wérante yu wóor ak kontekst bu wóor',
    'chat.council_consensus': 'Wàllu Wàll',
    'chat.council_members': 'Jëmm',
    'chat.council_reasoning': 'Xalaat',
    'status.online': 'Ci jàmm',
    // Tarteel
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Tànn Surah',
    'tarteel.loading_surah': 'Mi jëkk Surah bi...',
    'tarteel.listening_title': 'Mi ngi déglu...',
    'tarteel.listening_desc': 'Jàngal sa ayah bi ñu xàmme.',
    'tarteel.mic_error_title': 'Njumte Micro',
    'tarteel.mic_error_desc': 'Mic bi mënatul. Seenali ndigal yi ngir daje.',
    'tarteel.file_too_large_title': 'Denc bu mag lool',
    'tarteel.file_too_large_desc': 'Jàngal bi dafa rëy 10MB. Jébbal jàngal bu gàtt.',
    'tarteel.success_title': 'MashaAllah!',
    'tarteel.success_desc': 'Sa jàngal bi baax na.',
    'tarteel.correction_title': 'Sàmm laaj la',
    'tarteel.heard_label': 'Lanu déglu :',
    'tarteel.api_error_title': 'Njumte njaaréef',
    'tarteel.api_error_desc': 'Mënunu jëfandikoo sa jàngal. Delluleen.',
    'tarteel.tap_mic': 'Tappal micro ngir tàmbalee',
    'tarteel.overlay_analyzing': 'Mi ngi xool jàngal bi...',
    'tarteel.overlay_checking': 'Xool téem bu ñaan, tajweed, ak xool ci xam-xam.',
    'tarteel.ayah_label': 'Ayah',
    // Media
    'media.title': 'Média',
    'media.subtitle': 'Dal bu Contenu bu Islam',
    'media.intro': 'Gis contenu bu Islam bu ñu tànn ngir ñépp - video, podcast, ak mbind yu jàngale.',
    'media.loading': 'Mi jëkk video yi...',
    'media.empty': 'Video amul ci leegi.',
    'media.watch': 'Seet',
    'media.duration': 'Jëkk',
    // Events
    'events.title': 'Jëf',
    'events.subtitle': 'Jëf yu Jëmm',
    'events.intro': 'Jokk ak lecture, workshop, ak jëf yu bari ci sa dëkk.',
    'events.loading': 'Mi jëkk jëf yi...',
    'events.empty': 'Jëf amul ci leegi.',
    'events.register': 'Jëkk',
    'events.registered': 'Jëkk nañu',
    'events.location': 'Bët',
    'events.date': 'Bés',
    'events.attendees': 'Jëmm',
    // Shop
    'shop.title': 'Dëkk',
    'shop.shop_label': 'Butik',
    'shop.islamic': 'Lislaam',
    'shop.store': 'Bitik',
    'shop.browse_desc': 'Saytu te jënd ay produit Lislaam, ay téré ak yeneen yëf',
    'shop.waitlist_title': 'Merch previews. Bokku ci preorder.',
    'shop.waitlist_subtitle': 'Drop yu xóot, limi lekkool, design yu feesal. Déetul payement leegi—jël sa barab ngir ñu la xamal jëmm ak jëmm.',
    'shop.waitlist_exclusive': 'Dugub bu ndijoor bu jot ci kanam',
    'shop.waitlist_drop_hint': 'Drop yi ñuy wàcce ci ndimbel',
    'shop.preview': 'Preview',
    'shop.preorder': 'Preorder',
    'shop.waitlist_description': 'Bokku ci list bi ngir ñu la xamal bu drop bi ubbeeku.',
    'shop.waitlist_price_hint': 'Diir ci {price} {currency}',
    'shop.waitlist_email_placeholder': 'Imel ngir jot ci kanam',
    'shop.waitlist_cta': 'Xamleel ma jëmm',
    'shop.waitlist_joined_short': 'Yaa ngi ci list bi',
    'shop.waitlist_joined': 'Yaa ngi ci preorder list bi. Ñuy la xamle ci kanam.',
    'shop.waitlist_invalid_email': 'Dugal imel bu baax ngir dugg ci list bi.',
    'shop.order_created': 'Commande bi noppi na! Ñu ngi lay yobbu ci payement bi...',
    'shop.updated_qty': 'Yokku nañu limu yëf bi ci panier bi',
    'shop.added_to_cart': 'Yokku nañu ko ci panier bi',
    'shop.removed_from_cart': 'Dindi nañu ko ci panier bi',
    'shop.subtitle': 'Yëf yu Islam',
    'shop.intro': 'Gis yéeg yu wóor, téere, yëf yu bari, ak mbind yu bari ngir yokk sa xam-xam bu Islam.',
    'shop.loading': 'Mi jëkk yëf yi...',
    'shop.empty': 'Yëf amul ci leegi.',
    'shop.add_to_cart': 'Yokk ci panier',
    'shop.checkout': 'Jënd',
    'shop.price': 'Prix',
    'shop.in_stock': 'Am na',
    'shop.out_of_stock': 'Amul',
    'shop.category': 'Kategori',
    'shop.sort_by': 'Tàngale',
    'shop.all': 'Yépp',
    'shop.default': 'Bokk',
    'shop.price_low': 'Prix: Suuf ci kaw',
    'shop.price_high': 'Prix: Kaw ci suuf',
    'shop.name': 'Tur',
    'shop.shopping_cart': 'Panier',
    'shop.cart_empty': 'Sa panier dafa neen',
    'shop.items_in_cart': 'yëf',
    'shop.items_in_cart_plural': 'yëf',
    'shop.in_your_cart': 'ci sa panier',
    'shop.size': 'Génn',
    'shop.total': 'Jotal',
    'shop.proceed_checkout': 'Jënd',
    'shop.drop': 'Wàcc',
    'shop.drag_to_cart': '← Yéegal ci panier',
    'shop.select_size_drag': 'Tànn génn ngir yéegal',
    'shop.limited': 'Limité',
    'auth.required': 'Ndaxul Fàww',
    'auth.signin': 'Jóogleen ngir nànji',
    'nav.daily': 'Islaam Bépp Népp',
    'nav.chat': 'Waxtaan',
    'nav.videos': 'Video',
    'nav.events': 'Jëf',
    'nav.shop': 'Dëkk',
    'nav.library': 'Librairie',
    'nav.settings': 'Tànn',
    'nav.admin': 'Admin',
    'nav.circle': 'Wàllu Xam-xam',
    'nav.documents': 'Papira',
    'nav.signout': 'Jóggé',
    'nav.signin': 'Jóogle',
    'nav.home': 'Kër',
    // Library
    'library.title': 'Téerey Lislaam Digital',
    'library.subtitle': 'Jot ci téerey lislaam, mbind ak yëf yu bari',
    'library.search_placeholder': 'Seet téere ci tur, bindkat walla mbir...',
    'library.filter_category': 'Wàll',
    'library.filter_language': 'Làkk',
    'library.filter_format': 'Format',
    'library.all_categories': 'Wàll yépp',
    'library.all_languages': 'Làkk yépp',
    'library.all_formats': 'Format yépp',
    'library.downloads': 'yeb',
    'library.pages': 'xët',
    'library.file_size': 'MB',
    'library.download_button': 'Yeb',
    'library.featured': 'Siiw',
    'library.no_results': 'Amul téere bu méngoo ak li nga seet',
    'library.categories.quran': 'Al-Qur\'an',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqeedah',
    'library.categories.seerah': 'Seerah',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Jàng Arab',
    'library.categories.dua': 'Ñaan & Dikr',
    'library.categories.general': 'Bokk',
    'library.languages.ar': 'Arab',
    'library.languages.en': 'Angale',
    'library.languages.fr': 'Faransé',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Xam-xam bu Islaam\nCi Sa Loxo',
    'hero.subtitle': 'Sa plateforme bu Islam bu wóor : cër yu xam-xamkat, cër yu bés-bés, dal bu digital, jëmm, jëf, ak media.',
    'hero.popular': 'Lu ñu bëgg:',
    'hero.ask_now': 'Laaj leegi',
    // Footer
    'footer.contact': 'Jokkoolleen ak ñoom',
    'footer.description': 'Dal bi mu ngiy jox xam-xam bu dëggu ci Iislaam, jëmm ak xam-xamkat yi.',
    'footer.rights': 'Yenn sañ-saŋ yu mën.',
    // Index
    'index.what_title_prefix': 'Bàkkaleer AI ngir',
    'index.what_title_gradient': 'ndigël Islam',
    'index.what_subtitle': 'XamSaDine dafay jëfandikoo AI ak xam-xamkat yu xam-xam ngir jox tontu yu wur.',
    'index.guided_fatwa_title': 'Fatwaa tegu',
    'index.guided_fatwa_desc': "Laaj benn laaj bu Islam te jot tontu bu séentu ak wérante, hükm, dalil, te xamal te ndigël.",
    'index.try_it_now': 'Jéllal ko leegi',
    'index.daily_islam_title': 'Islaam bépp népp',
    'index.daily_islam_desc': "Tàmbalee guddi bu nekk ak ayah, hadith, du'aa, xam-xam bu ndaw, ak test bu wékki ngir tëral sa xam-xam.",
    'index.see_today': 'Gis leegi',
    'index.fiqh_map_title': 'Karte bu fiqh',
    'index.fiqh_map_desc': 'Seet téem yu fiqh ci ñeent madhab yi: jaamu, jëmbët, kër, njublaay ak xeetu dëkkuwaay.',
    'index.explore': 'Seet',
    'index.library_title': 'Téerey Digital',
    'index.library_desc': 'Jot ci téerey lislaam, PDF ak yëf yu jàngale',
    'index.browse_books': 'Seet téere yi',
    'index.how_title_prefix': 'Soppiko ci',
    'index.how_title_gradient': 'Sénégal ak Ummah bi',
    'index.how_subtitle': 'Tontu bépp di topp yoon bu sukk ak tëgg ci mbind yi wér.',
    'index.step1_title': 'Sa madhab, sa tontu',
    'index.step1_desc': "Fal sa madhab (Hanafi, Maliki, Shafi'i, Hanbali) te jot tontu yu nëbb ak sa seetaan.",
    'index.step2_title': 'Kontexte bu Sénégal',
    'index.step2_desc': 'XamSaDine xamu àdett yi, làkk (Wolof, Faransa), ak xaal yi muusleme yi ci Sénégal.',
    'index.step3_title': 'Tabaxlu ak dëgg',
    'index.step3_desc': "Fatwaa bépp di dox ci 5 yoon ak dalil yu wér ci Al-Qur'aan, Sunna, ak kitabu yu classik yu sa madhab.",
    'index.step4_title': 'Laaj yu Islam rekk',
    'index.step4_desc': 'XamSaDine di tànn ci ndigël bu Islam, di ñettal laaj yu dul jëm ci Islam ngir wër.',
    'index.final_cta_title': 'Ngir laaj sa laaj bu jëkk?',
    'index.final_cta_desc': "Tambalee session bu fatwaa tegu walla xool leegi ci 'Islaam bépp népp'. XamSaDine dina dox ak yaw.",
    'index.ask_question_btn': 'Laaj benn laaj',
    'index.see_daily_btn': 'Gis Islaam bépp népp',
    // Login
    'login.title': 'Dalal jàmm',
    'login.subtitle': 'Jóogle ngir jàll ci sa koont.',
    'login.create_account_title': 'Sàkk koont',
    'login.create_account_subtitle': 'Tàmbalee ci say jumtukaay.',
    'login.email': 'Email',
    'login.password': 'Mottali',
    'login.remember_me': 'Fii woon',
    'login.forgot_password': 'Mottali nga leen?',
    'login.processing': 'Mi dox...',
    'login.sign_in': 'Jóogle',
    'login.sign_up': 'Bind ak koont',
    'login.full_name': 'Tur bu wóor',
    'login.full_name_required': 'Tur bu wóor laaj na',
    'common.success': 'Jàmm rekk',
    'common.error': 'Njumte',
    'login.success_signed_in': 'Jóogle nañu la ak njàmm!',
    'login.success_signed_up': 'Koont bu bees nañu sàkk ko!',
    'login.failed': 'Jóogle da faaw',
    'login.failed_desc': 'Mënul jóogle',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Wacc! Xët bi gisul',
    'notfound.return_home': 'Dellusi kër',
    // Dashboard
    'dashboard.todays_reminder': 'Cuqalub bés bii',
    'dashboard.todays_prayer_times': 'Waxtu yi njulli ci bés bii',
    'dashboard.todays_action': 'Jëf bu bés bii',
    'dashboard.hadith_of_the_day': 'Hadith bu bés bii',
    'dashboard.source_authentic_hadith': 'Jëmm: Hadith bu dëggu',
    'dashboard.prayer_times': 'Waxtu yi njulli',
    'dashboard.enable_location': 'Jëkk bët ngir gis waxtu yi njulli',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Jël benn waxtu ngir xalaat ci aaya bu tey. Waxal ko ci sa njulli ak xalaat ci li mu tekki ci bés bii.',
    'dashboard.hadith_text': 'Yonent bi (jàmm ak moom) nee na: \'Nit ñi gën a baax ñooñu ñi gën a jariñu nit ñi.\'',
    'dashboard.sectionLabel': "Jàmmu Islam bii tey",
    'dashboard.titlePrefix': "Sa dëkk bu sukkandiku",
    'dashboard.titleHighlight': "cër yi tey",
    'dashboard.intro': "Tontu, duʿa, xam-xam yu ndaw ak quizu besub lakk – ngir nga dëppoo say xol ak Yàlla léegi léegi.",
    'dashboard.ayahOfTheDay': "Aaya bu bees",
    'dashboard.loading': "Mi ngi yeb…",
    'dashboard.ayahLoading': "Mi ngi yeb aaya bii…",
    'dashboard.ayahError': "Mënul yeb aaya bii.",
    'dashboard.todayLabel': "Tey",
    'dashboard.todaySummary': "Ci bés bii: benn aaya, benn hadith, benn duʿa ak benn jëf bu ndaw nga mën jëfandikoo.",
    'dashboard.openReminder': "Ubbi cuqalub bés bii",
    'dashboard.dailyDua': "Duʿa bu tey",
    'dashboard.dailyDuaLoading': "Mi ngi yeb duʿa bu tey…",
    'dashboard.dailyDuaError': "Mënul yeb duʿa bu tey.",
    'dashboard.smallFact': "Xam-xam bu ndaw",
    'dashboard.factLoading': "Mi ngi yeb xam-xam bu tey…",
    'dashboard.factError': "Mënul yeb xam-xam bu tey.",
    'dashboard.weeklyQuiz': "Quizu ayu-bés",
    'dashboard.weeklyQuizSubtitle': "Benn laaj, ñatte tollu.",
    'dashboard.easy': "Wóor-wóor",
    'dashboard.medium': "Dig-digg",
    'dashboard.advanced': "Xuux",
    'dashboard.checkAnswer': "Seet tontu bi",
    'dashboard.correctFeedback': "Baax na, tontu bi dëgg la.",
    'dashboard.wrongFeedbackPrefix': "Dul li. Wanaan: ",
    // Admin
    'admin.select_category': 'Tànn kategori',
    'admin.select_language': 'Tànn làkk',
    'admin.select_format': 'Tànn format',
    'admin.publisher_name': 'Tur bu sàkk mbind',
    // Errors
    'error.registration_failed': 'Jëkk da faaw',
    'error.checkout_failed': 'Jënd da faaw',
    'error.search_failed': 'Seet da faaw',
    'error.upload_failed': 'Yeb da faaw',
    'error.delete_failed': 'Mënul sàkk mbind bi.',
    'error.delete_document': 'Sàkk mbind'
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();

  const readStored = (): Language => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('xamsadine-language') as Language;
      if (saved && ['en', 'fr', 'wo'].includes(saved)) return saved;
    }
    if (user?.user_metadata?.language && ['en', 'fr', 'wo'].includes(user.user_metadata.language)) {
      return user.user_metadata.language;
    }
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(readStored);

  // Sync document lang and persist
  useEffect(() => {
    document.documentElement.lang = language;
    if (typeof window !== 'undefined') {
      localStorage.setItem('xamsadine-language', language);
    }
    if (user) {
      supabase.auth.updateUser({ data: { language } }).catch(() => {
        // ignore failure; keep UX fast
      });
    }
  }, [language, user]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const current = (translations as Record<string, Record<string, string>>)[language];
    const translate = (dict?: Record<string, string>) => {
      const value = dict?.[key];
      if (!value) return undefined;
      if (!params) return value;
      return Object.keys(params).reduce((acc, paramKey) => {
        const token = `{${paramKey}}`;
        return acc.replace(token, String(params[paramKey]));
      }, value);
    };

    const currentValue = translate(current);
    if (currentValue) return currentValue;

    const fallback = (translations as Record<string, Record<string, string>>).en;
    const fallbackValue = translate(fallback);
    if (fallbackValue) return fallbackValue;
    if (import.meta.env.DEV) {
      console.warn(`Missing translation key: ${key} for ${language}`);
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
