import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from '@/auth/AuthContext';

type Language = 'en' | 'fr' | 'wo';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  en: {
    'chat.placeholder': 'Ask me anything about Islam...',
    'chat.welcome': 'Asalamu alaikum, I am Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Get authentic Islamic answers from multiple scholarly perspectives.',
    'chat.thinking': 'Thinking...',
    'chat.error': 'Failed to get response. Please try again.',
    'chat.clear_history': 'Clear History',
    'chat.feature1.title': 'Multiple Perspectives',
    'chat.feature1.desc': 'Get answers from different Islamic schools of thought',
    'chat.feature2.title': 'Scholarly Sources',
    'chat.feature2.desc': 'Responses based on authentic Islamic sources',
    'chat.feature3.title': 'Contextual Answers',
    'chat.feature3.desc': 'Detailed explanations with proper context',
    'chat.council_consensus': 'Council Consensus',
    'chat.council_members': 'Members',
    'chat.council_reasoning': 'Reasoning',
    'status.online': 'Online',
    'chat.history_cleared': 'History Cleared',
    'chat.history_cleared_desc': 'Chat history has been cleared',
    'chat.invalid_response': 'Invalid response from server',
    // Council
    'council.no_members': 'No council members available',
    'council.model': 'Model',
    'council.creativity_level': 'Creativity Level',
    'council.consensus_analysis': 'Consensus Analysis',
    'council.consensus_score': 'Consensus Score',
    'council.processing_time': 'Processing Time',
    'council.confidence': 'Confidence',
    'council.ask_title': 'Ask the Council',
    'council.ask_placeholder': 'Ask a complex question and let the Council analyze it from multiple perspectives...',
    'council.deliberating': 'Council is Deliberating...',
    'council.ask_button': 'Ask Council',
    'council.upload.title': 'Title',
    'council.upload.title_placeholder': 'Document title',
    'council.upload.source': 'Source',
    'council.upload.source_placeholder': 'Document source (e.g., Islamic Text, Legal Document)',
    'council.upload.category': 'Category',
    'council.upload.content': 'Content',
    'council.upload.content_placeholder': 'Paste document content here',
    'council.upload.submit': 'Upload Document',
    'council.upload.uploading': 'Uploading...',
    'council.upload.category.general': 'General (All Agents)',
    'council.upload.category.fiqh': 'Fiqh Reasoning Agent',
    'council.upload.category.aqeedah': 'Aqeedah Boundary Agent',
    'council.upload.category.humility': 'Humility & Abstention Agent',
    'council.upload.category.context': 'Contemporary Context Agent',
    // Media
    'media.title': 'Media',
    'media.subtitle': 'Islamic Content Library',
    'media.intro': 'Discover Islamic content curated for all ages - videos, podcasts, and educational materials.',
    'media.loading': 'Loading videos...',
    'media.empty': 'No videos available yet.',
    'media.watch': 'Watch',
    'media.duration': 'Duration',
    // Events
    'events.title': 'Events',
    'events.subtitle': 'Community Events',
    'events.intro': 'Join lectures, workshops, and gatherings in your area.',
    'events.loading': 'Loading events...',
    'events.empty': 'No events scheduled yet.',
    'events.register': 'Register',
    'events.registered': 'Registered',
    'events.location': 'Location',
    'events.date': 'Date',
    'events.attendees': 'Attendees',
    'auth.required': 'Authentication Required',
    'auth.signin': 'Please sign in to ask questions',
    'nav.daily': 'Daily Islam',
    'nav.chat': 'Chat',
    'nav.videos': 'Videos',
    'nav.events': 'Events',
    'nav.library': 'Library',
    'nav.settings': 'Settings',
    'nav.admin': 'Admin',
    'nav.circle': 'Circle of Knowledge',
    'nav.documents': 'Documents',
    'nav.signout': 'Sign Out',
    'nav.signin': 'Sign In',
    'nav.rag_test': 'RAG Test',
    'nav.home': 'Home',
    // Library
    'library.title': 'Digital Islamic Library',
    'library.subtitle': 'Access a comprehensive collection of Islamic books, texts, and resources',
    'library.search_placeholder': 'Search books by title, author, or topic...',
    'library.filter_category': 'Category',
    'library.filter_language': 'Language',
    'library.filter_format': 'Format',
    'library.all_categories': 'All Categories',
    'library.all_languages': 'All Languages',
    'library.all_formats': 'All Formats',
    'library.downloads': 'downloads',
    'library.pages': 'pages',
    'library.file_size': 'MB',
    'library.download_button': 'Download',
    'library.featured': 'Featured',
    'library.no_results': 'No books found matching your criteria',
    'library.categories.quran': 'Quran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqeedah',
    'library.categories.seerah': 'Seerah',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Arabic Learning',
    'library.categories.dua': 'Dua & Dhikr',
    'library.categories.general': 'General',
    'library.languages.ar': 'Arabic',
    'library.languages.en': 'English',
    'library.languages.fr': 'French',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Islamic Knowledge\nAt Your Fingertips',
    'hero.subtitle': 'Your complete Islamic platform: scholarly guidance, daily inspiration, digital library, products, events, and media.',
    'hero.popular': 'Popular:',
    'hero.ask_now': 'Ask Now',
    'hero.get_started': 'Get Started',
    'hero.watch_video': 'Watch Video',
    // Footer
    'footer.contact': 'Contact Us',
    'footer.description': 'A platform dedicated to providing authentic Islamic knowledge through expert scholars.',
    'footer.rights': 'All Rights Reserved.',
    // Index (Landing)
    'index.what_title_prefix': 'An AI advisor for',
    'index.what_title_gradient': 'Islamic guidance',
    'index.what_subtitle': 'G�stuSaDine uses AI backed by expert scholars to provide structured, authentic answers to your questions about Islam.',
    'index.guided_fatwa_title': 'Guided Fatwa',
    'index.guided_fatwa_desc': "Ask any Islamic question and receive a structured answer with clarification, hukm, evidence, explanation, and advice.",
    'index.try_it_now': 'Try it now',
    'index.daily_islam_title': 'Daily Islam',
    'index.daily_islam_desc': "Start each day with an ayah, hadith, dua, a small fact, and a weekly quiz to keep your knowledge fresh.",
    'index.see_today': 'See today',
    'index.fiqh_map_title': 'Fiqh Map',
    'index.fiqh_map_desc': 'Explore fiqh themes across all four madhabs: worship, transactions, family, ethics, and local contexts.',
    'index.explore': 'Explore',
    'index.library_title': 'Digital Library',
    'index.library_desc': 'Access a comprehensive collection of Islamic books, PDFs, and educational resources',
    'index.browse_books': 'Browse Books',
    'index.how_title_prefix': 'Built for',
    'index.how_title_gradient': 'Senegal and the Ummah',
    'index.how_subtitle': 'Every answer follows a calm, structured flow rooted in authentic sources.',
    'index.step1_title': 'Your madhab, your answers',
    'index.step1_desc': "Choose your school of fiqh (Hanafi, Maliki, Shafi'i, Hanbali) and receive answers grounded in that tradition.",
    'index.step2_title': 'Senegalese context',
    'index.step2_desc': 'G�stuSaDine understands local customs, language (Wolof, French), and the realities of Muslim life in Senegal.',
    'index.step3_title': 'Structured & authenticated',
    'index.step3_desc': "Each fatwa flows through 5 steps with clear references from Qur'an, Hadith, and classical texts of your madhab.",
    'index.step4_title': 'Islamic questions only',
    'index.step4_desc': 'G�stuSaDine is dedicated to Islamic guidance. It gently declines non-Islamic topics to stay focused.',
    'index.final_cta_title': 'Ready to ask your first question?',
    'index.final_cta_desc': "Start a guided fatwa session or explore today's daily content. G�stuSaDine is here to walk with you.",
    'index.ask_question_btn': 'Ask a question',
    'index.see_daily_btn': 'See Daily Islam',
    // Login
    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to access your account.',
    'login.create_account_title': 'Create an Account',
    'login.create_account_subtitle': 'Enter your details to get started.',
    'login.email': 'Email address',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot your password?',
    'login.processing': 'Processing...',
    'login.sign_in': 'Sign In',
    'login.sign_up': 'Sign Up',
    'login.full_name': 'Full Name',
    'login.full_name_required': 'Full name is required',
    'common.success': 'Success',
    'common.error': 'Error',
    'login.success_signed_in': 'You have been logged in successfully!',
    'login.success_signed_up': 'Your account has been created successfully!',
    'login.failed': 'Login failed',
    'login.failed_desc': 'Could not sign in',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oops! Page not found',
    'notfound.return_home': 'Return to Home',
    // Dashboard
    'dashboard.todays_reminder': 'Today\'s Reminder',
    'dashboard.todays_prayer_times': 'Today\'s Prayer Times',
    'dashboard.todays_action': 'Today\'s Action',
    'dashboard.hadith_of_the_day': 'Hadith of the Day',
    'dashboard.source_authentic_hadith': 'Source: Authentic Hadith',
    'dashboard.prayer_times': 'Prayer Times',
    'dashboard.enable_location': 'Enable location to see prayer times',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Take a moment to reflect on today\'s ayah. Recite it in your prayers and contemplate its meaning throughout the day.',
    'dashboard.hadith_text': 'The Prophet (peace be upon him) said: \'The best of people are those who are most beneficial to people.\'',
    'dashboard.sectionLabel': 'Today\'s Islamic Knowledge',
    'dashboard.titlePrefix': 'Your personalized',
    'dashboard.titleHighlight': 'daily content',
    'dashboard.intro': 'Verses, duʿas, small facts, and weekly quizzes – to reconnect with Allah every day.',
    'dashboard.ayahOfTheDay': 'Verse of the Day',
    'dashboard.loading': 'Loading…',
    'dashboard.ayahLoading': 'Loading today\'s verse…',
    'dashboard.ayahError': 'Could not load today\'s verse.',
    'dashboard.todayLabel': 'Today',
    'dashboard.todaySummary': 'Today: one verse, one hadith, one duʿa, and a small action you can do.',
    'dashboard.openReminder': 'Open today\'s reminder',
    'dashboard.dailyDua': 'Today\'s Duʿa',
    'dashboard.dailyDuaLoading': 'Loading today\'s duʿa…',
    'dashboard.dailyDuaError': 'Could not load today\'s duʿa.',
    'dashboard.smallFact': 'Small Fact',
    'dashboard.factLoading': 'Loading today\'s fact…',
    'dashboard.factError': 'Could not load today\'s fact.',
    'dashboard.weeklyQuiz': 'Weekly Quiz',
    'dashboard.weeklyQuizSubtitle': 'One question, three levels.',
    'dashboard.easy': 'Easy',
    'dashboard.medium': 'Medium',
    'dashboard.advanced': 'Advanced',
    'dashboard.checkAnswer': 'Check Answer',
    'dashboard.correctFeedback': 'MashaAllah! Correct answer.',
    'dashboard.wrongFeedbackPrefix': 'Hint: ',
    // Quiz (Easy)
    'quiz.easy.question': "How many daily obligatory prayers are there in Islam?",
    'quiz.easy.options.0': "Three",
    'quiz.easy.options.1': "Five",
    'quiz.easy.options.2': "Seven",
    'quiz.easy.correct': "Five",
    'quiz.easy.hint': "Think of Fajr, Dhuhr, ʿAsr, Maghrib, ʿIshāʾ.",
    // Quiz (Medium)
    'quiz.medium.question': "In Maliki fiqh, what is one key condition for following an imām in congregational prayer?",
    'quiz.medium.options.0': "Standing directly in front of the imām",
    'quiz.medium.options.1': "Intending to follow the imām at the beginning of the prayer",
    'quiz.medium.options.2': "Reciting Sūrat al-Fātiḥah aloud with the imām",
    'quiz.medium.correct': "Intending to follow the imām at the beginning of the prayer",
    'quiz.medium.hint': "It relates to your niyyah (intention).",
    // Quiz (Advanced)
    'quiz.advanced.question': "According to many Maliki jurists, when can local custom (ʿurf) be used in rulings?",
    'quiz.advanced.options.0': "Whenever it is popular, even if it contradicts Qurʾān and Sunnah",
    'quiz.advanced.options.1': "When it does not oppose clear textual evidence and helps clarify contracts or practices",
    'quiz.advanced.options.2': "Only in matters of pure worship (ʿibādāt)",
    'quiz.advanced.correct': "When it does not oppose clear textual evidence and helps clarify contracts or practices",
    'quiz.advanced.hint': "Custom cannot override explicit texts.",
    // Admin
    'admin.select_category': 'Select category',
    'admin.select_language': 'Select language',
    'admin.select_format': 'Select format',
    'admin.publisher_name': 'Publisher name',
    // Errors
    'error.registration_failed': 'Registration failed',
    'error.checkout_failed': 'Checkout failed',
    'error.search_failed': 'Search failed',
    'error.upload_failed': 'Upload failed',
    'error.delete_failed': 'Could not delete document.',
    'error.delete_document': 'Delete document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Select a Surah',
    'tarteel.loading_surah': 'Loading Surah...',
    'tarteel.listening_title': 'Listening...',
    'tarteel.listening_desc': 'Please recite the highlighted verse.',
    'tarteel.mic_error_title': 'Microphone Error',
    'tarteel.mic_error_desc': 'Could not access microphone. Please ensure permissions are granted.',
    'tarteel.file_too_large_title': 'File Too Large',
    'tarteel.file_too_large_desc': 'Recording exceeds the 10MB limit. Please try a shorter recitation.',
    'tarteel.success_title': 'MashaAllah!',
    'tarteel.success_desc': 'Your recitation was correct.',
    'tarteel.correction_title': 'Correction Needed',
    'tarteel.heard_label': 'We heard:',
    'tarteel.api_error_title': 'Analysis Error',
    'tarteel.api_error_desc': 'Could not process your recitation. Please try again.',
    'tarteel.tap_mic': 'Tap microphone to start reciting',
    'tarteel.overlay_analyzing': 'Analyzing Recitation...',
    'tarteel.overlay_checking': 'Checking pronunciation, tajweed, and memorization accuracy.',
    'tarteel.ayah_label': 'Ayah',
    // Pricing
    'pricing.section_label': 'PRICING',
    'pricing.title_prefix': 'Choose Your',
    'pricing.title_gradient': 'Access Level',
    'pricing.subtitle': 'Start free, upgrade when you need more. All plans include authentic Islamic knowledge.',
    'pricing.tier.free.name': 'Free',
    'pricing.tier.free.description': 'Discovery and first exposure to the system',
    'pricing.tier.core.name': 'Core',
    'pricing.tier.core.description': 'The main experience for most users',
    'pricing.tier.pro.name': 'Pro',
    'pricing.tier.pro.description': 'For serious, long-term users',
    'pricing.most_popular': 'MOST POPULAR',
    'pricing.upgrade_prefix': 'Upgrade to',
    'pricing.get_started_free': 'Get Started Free',
    'pricing.per_month': '/month',
    'pricing.feature.chat_credits': '{count} chat credits/month',
    'pricing.feature.unlimited_credits': 'Unlimited chat credits',
    'pricing.feature.basic_responses': 'Basic AI responses',
    'pricing.feature.standard_time': 'Standard response time',
    'pricing.feature.specialized_modes': 'Specialized modes',
    'pricing.feature.personalized_themes': 'Personalized themes',
    'pricing.feature.full_customization': 'Full theme customization',
    'pricing.feature.memory': 'Memory & context',
    'pricing.feature.advanced_memory': 'Advanced memory',
    'pricing.feature.templates': 'Templates',
    'pricing.feature.all_templates': 'All templates',
    'pricing.feature.priority': 'Priority responses',
    'pricing.feature.advanced_planning': 'Advanced planning',
    'pricing.feature.early_access': 'Early access to features',
    'pricing.feature.all_modes': 'All specialized modes',
    'pricing.footer_note': 'All plans include access to Quran study tools, Fatwa requests, and Islamic guidance.'
  },
  fr: {
    'chat.placeholder': 'Demandez-moi quoi que ce soit sur l\'Islam...',
    'chat.welcome': 'Asalamu alaikum, je suis Anisah',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Obtenez des réponses islamiques authentiques de multiples perspectives savantes.',
    'chat.thinking': 'Réflexion...',
    'chat.error': 'Échec de la réponse. Veuillez réessayer.',
    'chat.history_cleared': 'Historique effacé',
    'chat.history_cleared_desc': 'L\'historique du chat a été effacé',
    'chat.invalid_response': 'Réponse invalide du serveur',
    'chat.clear_history': 'Effacer l\'historique',
    'chat.feature1.title': 'Perspectives multiples',
    'chat.feature1.desc': 'Obtenez des réponses de différentes écoles de pensée islamiques',
    'chat.feature2.title': 'Sources savantes',
    'chat.feature2.desc': 'Réponses basées sur des sources islamiques authentiques',
    'chat.feature3.title': 'Réponses contextuelles',
    'chat.feature3.desc': 'Explications détaillées avec le contexte approprié',
    'chat.council_consensus': 'Consensus du Conseil',
    'chat.council_members': 'Membres',
    'chat.council_reasoning': 'Raisonnement',
    'status.online': 'En ligne',
    // Council
    'council.no_members': 'Aucun membre du conseil disponible',
    'council.model': 'Modèle',
    'council.creativity_level': 'Niveau de Créativité',
    'council.consensus_analysis': 'Analyse de Consensus',
    'council.consensus_score': 'Score de Consensus',
    'council.processing_time': 'Temps de Traitement',
    'council.confidence': 'Confiance',
    'council.ask_title': 'Demander au Conseil',
    'council.ask_placeholder': 'Posez une question complexe et laissez le Conseil l\'analyser sous plusieurs perspectives...',
    'council.deliberating': 'Le Conseil délibère...',
    'council.ask_button': 'Demander au Conseil',
    'council.upload.title': 'Titre',
    'council.upload.title_placeholder': 'Titre du document',
    'council.upload.source': 'Source',
    'council.upload.source_placeholder': 'Source du document (ex: Texte Islamique, Document Juridique)',
    'council.upload.category': 'Catégorie',
    'council.upload.content': 'Contenu',
    'council.upload.content_placeholder': 'Collez le contenu du document ici',
    'council.upload.submit': 'Télécharger le Document',
    'council.upload.uploading': 'Téléchargement...',
    'council.upload.category.general': 'Général (Tous les Agents)',
    'council.upload.category.fiqh': 'Agent de Raisonnement Fiqh',
    'council.upload.category.aqeedah': 'Agent de Limite Aqida',
    'council.upload.category.humility': 'Agent d\'Humilité & Abstention',
    'council.upload.category.context': 'Agent de Contexte Contemporain',
    // Media
    'media.title': 'Média',
    'media.subtitle': 'Bibliothèque de contenu islamique',
    'media.intro': 'Découvrez du contenu islamique sélectionné pour tous les âges - vidéos, podcasts et matériels éducatifs.',
    'media.loading': 'Chargement des vidéos...',
    'media.empty': 'Aucune vidéo disponible pour le moment.',
    'media.watch': 'Regarder',
    'media.duration': 'Durée',
    // Events
    'events.title': 'Événements',
    'events.subtitle': 'Événements communautaires',
    'events.intro': 'Rejoignez des conférences, ateliers et rassemblements dans votre région.',
    'events.loading': 'Chargement des événements...',
    'events.empty': 'Aucun événement programmé pour le moment.',
    'events.register': 'S\'inscrire',
    'events.registered': 'Inscrit',
    'events.location': 'Lieu',
    'events.date': 'Date',
    'events.attendees': 'Participants',
    'auth.required': 'Authentification Requise',
    'auth.signin': 'Veuillez vous connecter pour poser des questions',
    'nav.daily': 'Islam Quotidien',
    'nav.chat': 'Chat',
    'nav.videos': 'Vidéos',
    'nav.events': 'Événements',
    'nav.library': 'Bibliothèque',
    'nav.settings': 'Paramètres',
    'nav.admin': 'Admin',
    'nav.circle': 'Cercle de Savoir',
    'nav.documents': 'Documents',
    'nav.signout': 'Déconnexion',
    'nav.signin': 'Connexion',
    'nav.rag_test': 'Test RAG',
    'nav.home': 'Accueil',
    // Library
    'library.title': 'Bibliothèque Numérique Islamique',
    'library.subtitle': 'Accédez à une collection complète de livres, textes et ressources islamiques',
    'library.search_placeholder': 'Rechercher par titre, auteur ou sujet...',
    'library.filter_category': 'Catégorie',
    'library.filter_language': 'Langue',
    'library.filter_format': 'Format',
    'library.all_categories': 'Toutes les catégories',
    'library.all_languages': 'Toutes les langues',
    'library.all_formats': 'Tous les formats',
    'library.downloads': 'téléchargements',
    'library.pages': 'pages',
    'library.file_size': 'Mo',
    'library.download_button': 'Télécharger',
    'library.featured': 'En vedette',
    'library.no_results': 'Aucun livre trouvé correspondant à vos critères',
    'library.categories.quran': 'Coran',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqida',
    'library.categories.seerah': 'Sira',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Apprentissage de l\'Arabe',
    'library.categories.dua': 'Dou\'a & Dhikr',
    'library.categories.general': 'Général',
    'library.languages.ar': 'Arabe',
    'library.languages.en': 'Anglais',
    'library.languages.fr': 'Français',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Connaissance Islamique\nÀ Portée de Main',
    'hero.subtitle': 'Votre plateforme islamique complète : conseils savants, inspiration quotidienne, bibliothèque numérique, produits, événements et médias.',
    'hero.popular': 'Populaire :',
    'hero.ask_now': 'Poser maintenant',
    'hero.get_started': 'Commencer',
    'hero.watch_video': 'Voir la vidéo',
    // Footer
    'footer.contact': 'Contactez-nous',
    'footer.description': 'Une plateforme dédiée à fournir un savoir islamique authentique à travers des savants experts.',
    'footer.rights': 'Tous droits réservés.',
    // Index
    'index.what_title_prefix': 'Un conseiller IA pour',
    'index.what_title_gradient': "l'orientation islamique",
    'index.what_subtitle': "G�stuSaDine utilise l'IA, soutenue par des savants, pour fournir des réponses authentiques et structurées à vos questions sur l'Islam.",
    'index.guided_fatwa_title': 'Fatwa guidée',
    'index.guided_fatwa_desc': "Posez toute question islamique et recevez une réponse structurée avec clarification, hukm, preuves, explication et conseils.",
    'index.try_it_now': 'Essayez maintenant',
    'index.daily_islam_title': 'Islam quotidien',
    'index.daily_islam_desc': "Commencez chaque jour avec un verset, un hadith, une dou'a, un petit fait, et un quiz hebdomadaire pour entretenir votre savoir.",
    'index.see_today': "Voir aujourd'hui",
    'index.fiqh_map_title': 'Carte du fiqh',
    'index.fiqh_map_desc': "Explorez les thèmes du fiqh à travers les quatre madhabs : adoration, transactions, famille, éthique, et contextes locaux.",
    'index.explore': 'Explorer',
    'index.library_title': 'Bibliothèque Numérique',
    'index.library_desc': 'Accédez à des livres islamiques, des PDF et des ressources éducatives',
    'index.browse_books': 'Parcourir les livres',
    'index.how_title_prefix': 'Conçu pour',
    'index.how_title_gradient': "le Sénégal et l'Oumma",
    'index.how_subtitle': "Chaque réponse suit un flux calme et structuré, ancré dans des sources authentiques.",
    'index.step1_title': 'Votre madhab, vos réponses',
    'index.step1_desc': "Choisissez votre école de fiqh (hanafi, maliki, shafi'i, hanbali) et recevez des réponses adaptées à cette tradition.",
    'index.step2_title': 'Contexte sénégalais',
    'index.step2_desc': "G�stuSaDine comprend les coutumes locales, la langue (wolof, français) et la réalité de la vie musulmane au Sénégal.",
    'index.step3_title': 'Structuré et authentifié',
    'index.step3_desc': "Chaque fatwa suit 5 étapes avec des références claires au Coran, à la Sunna et aux textes classiques de votre madhab.",
    'index.step4_title': 'Questions islamiques uniquement',
    'index.step4_desc': "G�stuSaDine est dédié à l'orientation islamique et décline les sujets non islamiques pour rester focalisé.",
    'index.final_cta_title': 'Prêt à poser votre première question ?',
    'index.final_cta_desc': "Lancez une session de fatwa guidée ou explorez le contenu quotidien d'aujourd'hui. G�stuSaDine vous accompagne.",
    'index.ask_question_btn': 'Poser une question',
    'index.see_daily_btn': 'Voir Islam quotidien',
    // Login
    'login.title': 'Bon retour',
    'login.subtitle': 'Connectez-vous pour accéder à votre compte.',
    'login.create_account_title': 'Créer un compte',
    'login.create_account_subtitle': 'Entrez vos informations pour commencer.',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.remember_me': 'Se souvenir de moi',
    'login.forgot_password': 'Mot de passe oublié ?',
    'login.processing': 'Traitement...',
    'login.sign_in': 'Connexion',
    'login.sign_up': 'Inscription',
    'login.full_name': 'Nom complet',
    'login.full_name_required': 'Le nom complet est requis',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'login.success_signed_in': 'Vous êtes connecté avec succès !',
    'login.success_signed_up': 'Votre compte a été créé avec succès !',
    'login.failed': 'Échec de la connexion',
    'login.failed_desc': 'Impossible de se connecter',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Oups ! Page introuvable',
    'notfound.return_home': "Retour à l'accueil",
    // Dashboard
    'dashboard.todays_reminder': 'Rappel du jour',
    'dashboard.todays_prayer_times': 'Heures de prière du jour',
    'dashboard.todays_action': 'Action du jour',
    'dashboard.hadith_of_the_day': 'Hadith du jour',
    'dashboard.source_authentic_hadith': 'Source : Hadith authentique',
    'dashboard.prayer_times': 'Heures de prière',
    'dashboard.enable_location': 'Activez la localisation pour voir les heures de prière',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Prenez un moment pour réfléchir à l\'ayah du jour. Récitez-la dans vos prières et méditez sur sa signification tout au long de la journée.',
    'dashboard.hadith_text': 'Le Prophète (paix sur lui) a dit : \'Les meilleurs des gens sont ceux qui sont les plus bénéfiques aux gens.\'',
    'dashboard.sectionLabel': 'Savoir Islamique du Jour',
    'dashboard.titlePrefix': 'Votre contenu',
    'dashboard.titleHighlight': 'quotidien personnalisé',
    'dashboard.intro': 'Versets, duʿas, petits faits et quiz hebdomadaires – pour renouer avec Allah chaque jour.',
    'dashboard.ayahOfTheDay': 'Verset du Jour',
    'dashboard.loading': 'Chargement…',
    'dashboard.ayahLoading': 'Chargement du verset du jour…',
    'dashboard.ayahError': 'Impossible de charger le verset du jour.',
    'dashboard.todayLabel': 'Aujourd\'hui',
    'dashboard.todaySummary': 'Aujourd\'hui : un verset, un hadith, une duʿa, et une petite action que vous pouvez faire.',
    'dashboard.openReminder': 'Ouvrir le rappel du jour',
    'dashboard.dailyDua': 'Duʿa du Jour',
    'dashboard.dailyDuaLoading': 'Chargement de la duʿa du jour…',
    'dashboard.dailyDuaError': 'Impossible de charger la duʿa du jour.',
    'dashboard.smallFact': 'Petit Fait',
    'dashboard.factLoading': 'Chargement du fait du jour…',
    'dashboard.factError': 'Impossible de charger le fait du jour.',
    'dashboard.weeklyQuiz': 'Quiz Hebdomadaire',
    'dashboard.weeklyQuizSubtitle': 'Une question, trois niveaux.',
    'dashboard.easy': 'Facile',
    'dashboard.medium': 'Moyen',
    'dashboard.advanced': 'Avancé',
    'dashboard.checkAnswer': 'Vérifier la Réponse',
    'dashboard.correctFeedback': 'MashaAllah ! Bonne réponse.',
    'dashboard.wrongFeedbackPrefix': 'Indice : ',
    // Quiz (Easy)
    'quiz.easy.question': "Combien de prières obligatoires quotidiennes y a-t-il en Islam ?",
    'quiz.easy.options.0': "Trois",
    'quiz.easy.options.1': "Cinq",
    'quiz.easy.options.2': "Sept",
    'quiz.easy.correct': "Cinq",
    'quiz.easy.hint': "Pense à Fajr, Dhuhr, ʿAsr, Maghrib, ʿIshāʾ.",
    // Quiz (Medium)
    'quiz.medium.question': "En fiqh malikite, quelle est une condition clé pour suivre l’imam en prière collective ?",
    'quiz.medium.options.0': "Se tenir directement devant l’imam",
    'quiz.medium.options.1': "Avoir l’intention de suivre l’imam au début de la prière",
    'quiz.medium.options.2': "Réciter la Fātiḥa à voix haute avec l’imam",
    'quiz.medium.correct': "Avoir l’intention de suivre l’imam au début de la prière",
    'quiz.medium.hint': "Cela concerne la niyyah (intention).",
    // Quiz (Advanced)
    'quiz.advanced.question': "Selon de nombreux juristes malikites, quand peut-on utiliser la coutume locale (ʿurf) dans les règles ?",
    'quiz.advanced.options.0': "Chaque fois qu’elle est populaire, même si elle contredit le Coran et la Sunna",
    'quiz.advanced.options.1': "Lorsqu’elle n’oppose pas un texte clair et aide à clarifier des contrats ou pratiques",
    'quiz.advanced.options.2': "Uniquement dans les questions d’adoration (ʿibādāt)",
    'quiz.advanced.correct': "Lorsqu’elle n’oppose pas un texte clair et aide à clarifier des contrats ou pratiques",
    'quiz.advanced.hint': "La coutume ne peut pas contredire des textes explicites.",
    // Admin
    'admin.select_category': 'Sélectionner la catégorie',
    'admin.select_language': 'Sélectionner la langue',
    'admin.select_format': 'Sélectionner le format',
    'admin.publisher_name': 'Nom de l\'éditeur',
    // Errors
    'error.registration_failed': 'Échec de l\'inscription',
    'error.checkout_failed': 'Échec du paiement',
    'error.search_failed': 'Échec de la recherche',
    'error.upload_failed': 'Échec du téléchargement',
    'error.delete_failed': 'Impossible de supprimer le document.',
    'error.delete_document': 'Supprimer le document'
    ,
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Sélectionner une sourate',
    'tarteel.loading_surah': 'Chargement de la sourate...',
    'tarteel.listening_title': 'Écoute en cours...',
    'tarteel.listening_desc': 'Veuillez réciter le verset en surbrillance.',
    'tarteel.mic_error_title': 'Erreur de microphone',
    'tarteel.mic_error_desc': 'Impossible d’accéder au microphone. Vérifiez les permissions.',
    'tarteel.file_too_large_title': 'Fichier trop volumineux',
    'tarteel.file_too_large_desc': 'L’enregistrement dépasse 10 Mo. Essayez une récitation plus courte.',
    'tarteel.success_title': 'MashaAllah !',
    'tarteel.success_desc': 'Votre récitation est correcte.',
    'tarteel.correction_title': 'Correction nécessaire',
    'tarteel.heard_label': 'Nous avons entendu :',
    'tarteel.api_error_title': 'Erreur d’analyse',
    'tarteel.api_error_desc': 'Impossible de traiter votre récitation. Veuillez réessayer.',
    'tarteel.tap_mic': 'Appuyez sur le micro pour commencer',
    'tarteel.overlay_analyzing': 'Analyse de la récitation...',
    'tarteel.overlay_checking': 'Vérification de la prononciation, du tajwid et de la mémorisation.',
    'tarteel.ayah_label': 'Verset',
    // Pricing
    'pricing.section_label': 'TARIFS',
    'pricing.title_prefix': 'Choisissez Votre',
    'pricing.title_gradient': 'Niveau d\'Accès',
    'pricing.subtitle': 'Commencez gratuitement, mettez à niveau quand vous avez besoin de plus. Tous les plans incluent un savoir islamique authentique.',
    'pricing.tier.free.name': 'Gratuit',
    'pricing.tier.free.description': 'Découverte et première exposition au système',
    'pricing.tier.core.name': 'Core',
    'pricing.tier.core.description': 'L\'expérience principale pour la plupart des utilisateurs',
    'pricing.tier.pro.name': 'Pro',
    'pricing.tier.pro.description': 'Pour les utilisateurs sérieux à long terme',
    'pricing.most_popular': 'LE PLUS POPULAIRE',
    'pricing.upgrade_prefix': 'Passer à',
    'pricing.get_started_free': 'Commencer Gratuitement',
    'pricing.per_month': '/mois',
    'pricing.feature.chat_credits': '{count} crédits chat/mois',
    'pricing.feature.unlimited_credits': 'Crédits chat illimités',
    'pricing.feature.basic_responses': 'Réponses IA basiques',
    'pricing.feature.standard_time': 'Temps de réponse standard',
    'pricing.feature.specialized_modes': 'Modes spécialisés',
    'pricing.feature.personalized_themes': 'Thèmes personnalisés',
    'pricing.feature.full_customization': 'Personnalisation complète du thème',
    'pricing.feature.memory': 'Mémoire et contexte',
    'pricing.feature.advanced_memory': 'Mémoire avancée',
    'pricing.feature.templates': 'Modèles',
    'pricing.feature.all_templates': 'Tous les modèles',
    'pricing.feature.priority': 'Réponses prioritaires',
    'pricing.feature.advanced_planning': 'Planification avancée',
    'pricing.feature.early_access': 'Accès anticipé aux fonctionnalités',
    'pricing.feature.all_modes': 'Tous les modes spécialisés',
    'pricing.footer_note': 'Tous les plans incluent l\'accès aux outils d\'étude du Coran, aux demandes de fatwa et aux conseils islamiques.'
  },
  wo: {
    'chat.placeholder': 'Nan ma wax lé l\'Islaam...',
    'chat.welcome': 'Asalamu alaikum, man Anisah la',
    'chat.welcome_logo_alt': 'Anisah',
    'chat.welcome.subtitle': 'Wañ japp ndax mi jëmm ju Iislaam ji yore wax yu bari xam-xam.',
    'chat.thinking': 'Mi nangu tànn...',
    'chat.error': 'Wula ju topp. Jàppleen ndax.',
    'chat.clear_history': 'Séetal jëfandikukat',
    'chat.feature1.title': 'Xalaat yu bari',
    'chat.feature1.desc': 'Jot tontu ci seetaan yu bari yu Islam',
    'chat.feature2.title': 'Jëmm yu xam-xam',
    'chat.feature2.desc': 'Tontu yu nëbb ci jëmm yu dëggu yu Islam',
    'chat.feature3.title': 'Tontu yu kontekst',
    'chat.feature3.desc': 'Wérante yu wóor ak kontekst bu wóor',
    'chat.council_consensus': 'Wàllu Wàll',
    'chat.council_members': 'Jëmm',
    'chat.council_reasoning': 'Xalaat',
    'status.online': 'Ci jàmm',
    'chat.history_cleared': 'Séetal jëfandikukat',
    'chat.history_cleared_desc': 'Jëfandikukat bi dañu ko sëf',
    'chat.invalid_response': 'Tontu bu wórul',
    // Council
    'council.no_members': 'Amul kénn ci kureel gi',
    'council.model': 'Royuwaay',
    'council.creativity_level': 'Melokaanu Xalaat',
    'council.consensus_analysis': 'Xool Mbootaay',
    'council.consensus_score': 'Natt Mbootaay',
    'council.processing_time': 'Waxtu Liggeey',
    'council.confidence': 'Wóolu',
    'council.ask_title': 'Laaj Kureel gi',
    'council.ask_placeholder': 'Laaj laaj bu xóot te nangu Kureel gi xool ko...',
    'council.deliberating': 'Kureel gi ngi waxtaan...',
    'council.ask_button': 'Laaj Kureel',
    'council.upload.title': 'Tur',
    'council.upload.title_placeholder': 'Turu mbind mi',
    'council.upload.source': 'Jëmm',
    'council.upload.source_placeholder': 'Jëmmu mbind mi (ex: Kàllaama Lislaam)',
    'council.upload.category': 'Wàll',
    'council.upload.content': 'Ëmb',
    'council.upload.content_placeholder': 'Dugal ëmb bi fii',
    'council.upload.submit': 'Yeb Mbind mi',
    'council.upload.uploading': 'Mi ngi yeb...',
    'council.upload.category.general': 'Mbooleem (Agents yépp)',
    'council.upload.category.fiqh': 'Agent Fiqh',
    'council.upload.category.aqeedah': 'Agent Aqeedah',
    'council.upload.category.humility': 'Agent Humilité',
    'council.upload.category.context': 'Agent Kontexte',
    // Tarteel
    'tarteel.title': 'Qirah',
    'tarteel.select_surah': 'Tànn Surah',
    'tarteel.loading_surah': 'Mi jëkk Surah bi...',
    'tarteel.listening_title': 'Mi ngi déglu...',
    'tarteel.listening_desc': 'Jàngal sa ayah bi ñu xàmme.',
    'tarteel.mic_error_title': 'Njumte Micro',
    'tarteel.mic_error_desc': 'Mic bi mënatul. Seenali ndigal yi ngir daje.',
    'tarteel.file_too_large_title': 'Denc bu mag lool',
    'tarteel.file_too_large_desc': 'Jàngal bi dafa rëy 10MB. Jébbal jàngal bu gàtt.',
    'tarteel.success_title': 'MashaAllah!',
    'tarteel.success_desc': 'Sa jàngal bi baax na.',
    'tarteel.correction_title': 'Sàmm laaj la',
    'tarteel.heard_label': 'Lanu déglu :',
    'tarteel.api_error_title': 'Njumte njaaréef',
    'tarteel.api_error_desc': 'Mënunu jëfandikoo sa jàngal. Delluleen.',
    'tarteel.tap_mic': 'Tappal micro ngir tàmbalee',
    'tarteel.overlay_analyzing': 'Mi ngi xool jàngal bi...',
    'tarteel.overlay_checking': 'Xool téem bu ñaan, tajweed, ak xool ci xam-xam.',
    'tarteel.ayah_label': 'Ayah',
    // Media
    'media.title': 'Média',
    'media.subtitle': 'Dal bu Contenu bu Islam',
    'media.intro': 'Gis contenu bu Islam bu ñu tànn ngir ñépp - video, podcast, ak mbind yu jàngale.',
    'media.loading': 'Mi jëkk video yi...',
    'media.empty': 'Video amul ci leegi.',
    'media.watch': 'Seet',
    'media.duration': 'Jëkk',
    // Events
    'events.title': 'Jëf',
    'events.subtitle': 'Jëf yu Jëmm',
    'events.intro': 'Jokk ak lecture, workshop, ak jëf yu bari ci sa dëkk.',
    'events.loading': 'Mi jëkk jëf yi...',
    'events.empty': 'Jëf amul ci leegi.',
    'events.register': 'Jëkk',
    'events.registered': 'Jëkk nañu',
    'events.location': 'Bët',
    'events.date': 'Bés',
    'events.attendees': 'Jëmm',
    'auth.required': 'Ndaxul Fàww',
    'auth.signin': 'Jóogleen ngir nànji',
    'nav.daily': 'Islaam Bépp Népp',
    'nav.chat': 'Waxtaan',
    'nav.videos': 'Video',
    'nav.events': 'Jëf',
    'nav.library': 'Librairie',
    'nav.settings': 'Tànn',
    'nav.admin': 'Admin',
    'nav.circle': 'Wàllu Xam-xam',
    'nav.documents': 'Papira',
    'nav.signout': 'Jóggé',
    'nav.signin': 'Jóogle',
    'nav.rag_test': 'Test RAG',
    'nav.home': 'Kër',
    // Library
    'library.title': 'Téerey Lislaam Digital',
    'library.subtitle': 'Jot ci téerey lislaam, mbind ak yëf yu bari',
    'library.search_placeholder': 'Seet téere ci tur, bindkat walla mbir...',
    'library.filter_category': 'Wàll',
    'library.filter_language': 'Làkk',
    'library.filter_format': 'Format',
    'library.all_categories': 'Wàll yépp',
    'library.all_languages': 'Làkk yépp',
    'library.all_formats': 'Format yépp',
    'library.downloads': 'yeb',
    'library.pages': 'xët',
    'library.file_size': 'MB',
    'library.download_button': 'Yeb',
    'library.featured': 'Siiw',
    'library.no_results': 'Amul téere bu méngoo ak li nga seet',
    'library.categories.quran': 'Al-Qur\'an',
    'library.categories.hadith': 'Hadith',
    'library.categories.fiqh': 'Fiqh',
    'library.categories.aqeedah': 'Aqeedah',
    'library.categories.seerah': 'Seerah',
    'library.categories.tafsir': 'Tafsir',
    'library.categories.arabic': 'Jàng Arab',
    'library.categories.dua': 'Ñaan & Dikr',
    'library.categories.general': 'Bokk',
    'library.languages.ar': 'Arab',
    'library.languages.en': 'Angale',
    'library.languages.fr': 'Faransé',
    'library.languages.wo': 'Wolof',
    'library.formats.pdf': 'PDF',
    'library.formats.epub': 'EPUB',
    'library.formats.mobi': 'MOBI',
    'library.formats.audio': 'Audio',
    // Hero
    'hero.heading': 'Xam-xam bu Islaam\nCi Sa Loxo',
    'hero.subtitle': 'Sa plateforme bu Islam bu wóor : cër yu xam-xamkat, cër yu bés-bés, dal bu digital, jëmm, jëf, ak media.',
    'hero.popular': 'Lu ñu bëgg:',
    'hero.ask_now': 'Laaj leegi',
    'hero.get_started': 'Tàmbalee',
    'hero.watch_video': 'Seet video',
    // Footer
    'footer.contact': 'Jokkoolleen ak ñoom',
    'footer.description': 'Dal bi mu ngiy jox xam-xam bu dëggu ci Iislaam, jëmm ak xam-xamkat yi.',
    'footer.rights': 'Yenn sañ-saŋ yu mën.',
    // Index
    'index.what_title_prefix': 'Bàkkaleer AI ngir',
    'index.what_title_gradient': 'ndigël Islam',
    'index.what_subtitle': 'G�stuSaDine dafay jëfandikoo AI ak xam-xamkat yu xam-xam ngir jox tontu yu wur.',
    'index.guided_fatwa_title': 'Fatwaa tegu',
    'index.guided_fatwa_desc': "Laaj benn laaj bu Islam te jot tontu bu séentu ak wérante, hükm, dalil, te xamal te ndigël.",
    'index.try_it_now': 'Jéllal ko leegi',
    'index.daily_islam_title': 'Islaam bépp népp',
    'index.daily_islam_desc': "Tàmbalee guddi bu nekk ak ayah, hadith, du'aa, xam-xam bu ndaw, ak test bu wékki ngir tëral sa xam-xam.",
    'index.see_today': 'Gis leegi',
    'index.fiqh_map_title': 'Karte bu fiqh',
    'index.fiqh_map_desc': 'Seet téem yu fiqh ci ñeent madhab yi: jaamu, jëmbët, kër, njublaay ak xeetu dëkkuwaay.',
    'index.explore': 'Seet',
    'index.library_title': 'Téerey Digital',
    'index.library_desc': 'Jot ci téerey lislaam, PDF ak yëf yu jàngale',
    'index.browse_books': 'Seet téere yi',
    'index.how_title_prefix': 'Soppiko ci',
    'index.how_title_gradient': 'Sénégal ak Ummah bi',
    'index.how_subtitle': 'Tontu bépp di topp yoon bu sukk ak tëgg ci mbind yi wér.',
    'index.step1_title': 'Sa madhab, sa tontu',
    'index.step1_desc': "Fal sa madhab (Hanafi, Maliki, Shafi'i, Hanbali) te jot tontu yu nëbb ak sa seetaan.",
    'index.step2_title': 'Kontexte bu Sénégal',
    'index.step2_desc': 'G�stuSaDine xamu àdett yi, làkk (Wolof, Faransa), ak xaal yi muusleme yi ci Sénégal.',
    'index.step3_title': 'Tabaxlu ak dëgg',
    'index.step3_desc': "Fatwaa bépp di dox ci 5 yoon ak dalil yu wér ci Al-Qur'aan, Sunna, ak kitabu yu classik yu sa madhab.",
    'index.step4_title': 'Laaj yu Islam rekk',
    'index.step4_desc': 'G�stuSaDine di tànn ci ndigël bu Islam, di ñettal laaj yu dul jëm ci Islam ngir wër.',
    'index.final_cta_title': 'Ngir laaj sa laaj bu jëkk?',
    'index.final_cta_desc': "Tambalee session bu fatwaa tegu walla xool leegi ci 'Islaam bépp népp'. G�stuSaDine dina dox ak yaw.",
    'index.ask_question_btn': 'Laaj benn laaj',
    'index.see_daily_btn': 'Gis Islaam bépp népp',
    // Login
    'login.title': 'Dalal jàmm',
    'login.subtitle': 'Jóogle ngir jàll ci sa koont.',
    'login.create_account_title': 'Sàkk koont',
    'login.create_account_subtitle': 'Tàmbalee ci say jumtukaay.',
    'login.email': 'Email',
    'login.password': 'Mottali',
    'login.remember_me': 'Fii woon',
    'login.forgot_password': 'Mottali nga leen?',
    'login.processing': 'Mi dox...',
    'login.sign_in': 'Jóogle',
    'login.sign_up': 'Bind ak koont',
    'login.full_name': 'Tur bu wóor',
    'login.full_name_required': 'Tur bu wóor laaj na',
    'common.success': 'Jàmm rekk',
    'common.error': 'Njumte',
    'login.success_signed_in': 'Jóogle nañu la ak njàmm!',
    'login.success_signed_up': 'Koont bu bees nañu sàkk ko!',
    'login.failed': 'Jóogle da faaw',
    'login.failed_desc': 'Mënul jóogle',
    // NotFound
    'notfound.title': '404',
    'notfound.message': 'Wacc! Xët bi gisul',
    'notfound.return_home': 'Dellusi kër',
    // Dashboard
    'dashboard.todays_reminder': 'Cuqalub bés bii',
    'dashboard.todays_prayer_times': 'Waxtu yi njulli ci bés bii',
    'dashboard.todays_action': 'Jëf bu bés bii',
    'dashboard.hadith_of_the_day': 'Hadith bu bés bii',
    'dashboard.source_authentic_hadith': 'Jëmm: Hadith bu dëggu',
    'dashboard.prayer_times': 'Waxtu yi njulli',
    'dashboard.enable_location': 'Jëkk bët ngir gis waxtu yi njulli',
    'dashboard.prayer.fajr': 'Fajr',
    'dashboard.prayer.dhuhr': 'Dhuhr',
    'dashboard.prayer.asr': 'Asr',
    'dashboard.prayer.maghrib': 'Maghrib',
    'dashboard.prayer.isha': 'Isha',
    'dashboard.action_text': 'Jël benn waxtu ngir xalaat ci aaya bu tey. Waxal ko ci sa njulli ak xalaat ci li mu tekki ci bés bii.',
    'dashboard.hadith_text': 'Yonent bi (jàmm ak moom) nee na: \'Nit ñi gën a baax ñooñu ñi gën a jariñu nit ñi.\'',
    'dashboard.sectionLabel': "Jàmmu Islam bii tey",
    'dashboard.titlePrefix': "Sa dëkk bu sukkandiku",
    'dashboard.titleHighlight': "cër yi tey",
    'dashboard.intro': "Tontu, duʿa, xam-xam yu ndaw ak quizu besub lakk – ngir nga dëppoo say xol ak Yàlla léegi léegi.",
    'dashboard.ayahOfTheDay': "Aaya bu bees",
    'dashboard.loading': "Mi ngi yeb…",
    'dashboard.ayahLoading': "Mi ngi yeb aaya bii…",
    'dashboard.ayahError': "Mënul yeb aaya bii.",
    // Quiz (Easy)
    'quiz.easy.question': "Njulli yu séentu bu bépp bés ñaata la ci Islam ?",
    'quiz.easy.options.0': "Ñetti",
    'quiz.easy.options.1': "Juroom",
    'quiz.easy.options.2': "Juróom-ñaari",
    'quiz.easy.correct': "Juroom",
    'quiz.easy.hint': "Xool Fajr, Dhuhr, ʿAsr, Maghrib, ʿIshāʾ.",
    // Quiz (Medium)
    'quiz.medium.question': "Ci fiqh Maliki, lan la benn xaalis bu am solo ngir topp imâm ci njulli bu jàmm ?",
    'quiz.medium.options.0': "Taxaw ci kanam imâm",
    'quiz.medium.options.1': "Niyyah ngir topp imâm ci tàmbali njulli",
    'quiz.medium.options.2': "Waxal Sūrat al-Fātiḥah ci kaw ak imâm",
    'quiz.medium.correct': "Niyyah ngir topp imâm ci tàmbali njulli",
    'quiz.medium.hint': "Li jëm ci sa niyyah.",
    // Quiz (Advanced)
    'quiz.advanced.question': "Ni jurist yu bari ci Maliki wax, kan la ʿurf (àdetu dëkkuwaay) mën cee jariñu ci tegtal yi ?",
    'quiz.advanced.options.0': "Saa su nekk bu ne, su mel la muy di wacc Qurʼaan ak Sunna",
    'quiz.advanced.options.1': "Su mu du séen ak mbind yu wér te mu dëgëral jëmmante ak jumtukaay yi",
    'quiz.advanced.options.2': "Ci mbiri jaamu rekk (ʿibādāt)",
    'quiz.advanced.correct': "Su mu du séen ak mbind yu wér te mu dëgëral jëmmante ak jumtukaay yi",
    'quiz.advanced.hint': "Àdet mënul weñ wott mbind yu wér.",
    'dashboard.todayLabel': "Tey",
    'dashboard.todaySummary': "Ci bés bii: benn aaya, benn hadith, benn duʿa ak benn jëf bu ndaw nga mën jëfandikoo.",
    'dashboard.openReminder': "Ubbi cuqalub bés bii",
    'dashboard.dailyDua': "Duʿa bu tey",
    'dashboard.dailyDuaLoading': "Mi ngi yeb duʿa bu tey…",
    'dashboard.dailyDuaError': "Mënul yeb duʿa bu tey.",
    'dashboard.smallFact': "Xam-xam bu ndaw",
    'dashboard.factLoading': "Mi ngi yeb xam-xam bu tey…",
    'dashboard.factError': "Mënul yeb xam-xam bu tey.",
    'dashboard.weeklyQuiz': "Quizu ayu-bés",
    'dashboard.weeklyQuizSubtitle': "Benn laaj, ñatte tollu.",
    'dashboard.easy': "Wóor-wóor",
    'dashboard.medium': "Dig-digg",
    'dashboard.advanced': "Xuux",
    'dashboard.checkAnswer': "Seet tontu bi",
    'dashboard.correctFeedback': "Baax na, tontu bi dëgg la.",
    'dashboard.wrongFeedbackPrefix': "Dul li. Wanaan: ",
    // Admin
    'admin.select_category': 'Tànn kategori',
    'admin.select_language': 'Tànn làkk',
    'admin.select_format': 'Tànn format',
    'admin.publisher_name': 'Tur bu sàkk mbind',
    // Errors
    'error.registration_failed': 'Jëkk da faaw',
    'error.checkout_failed': 'Jënd da faaw',
    'error.search_failed': 'Seet da faaw',
    'error.upload_failed': 'Yeb da faaw',
    'error.delete_failed': 'Mënul sàkk mbind bi.',
    'error.delete_document': 'Sàkk mbind',
    // Pricing
    'pricing.section_label': 'JËND',
    'pricing.title_prefix': 'Tànn Sa',
    'pricing.title_gradient': 'Tollu Jëkk',
    'pricing.subtitle': 'Tàmbalee benn fees, yàgg bu nga soxla. Plan yépp ngi am jëmm bu Islam bu dëgg.',
    'pricing.tier.free.name': 'Fees',
    'pricing.tier.free.description': 'Gis ak xool ci système bi',
    'pricing.tier.core.name': 'Core',
    'pricing.tier.core.description': 'Tàmbaliku bu mag ci jëfandikukat yi',
    'pricing.tier.pro.name': 'Pro',
    'pricing.tier.pro.description': 'Ci jëfandikukat yu baax yu guddi gu gënn',
    'pricing.most_popular': 'BU ÑU GËNA BËGG',
    'pricing.upgrade_prefix': 'Yàgg ci',
    'pricing.get_started_free': 'Tàmbalee Fees',
    'pricing.per_month': '/weer',
    'pricing.feature.chat_credits': '{count} crédit waxtaan/weer',
    'pricing.feature.unlimited_credits': 'Crédit waxtaan du wóor',
    'pricing.feature.basic_responses': 'Tontu AI yu njëkk',
    'pricing.feature.standard_time': 'Waxtu tontu bu standaard',
    'pricing.feature.specialized_modes': 'Yoon yu spécial',
    'pricing.feature.personalized_themes': 'Thème yu sukkandiku',
    'pricing.feature.full_customization': 'Sukkandiku thème mu wóor',
    'pricing.feature.memory': 'Xam-xam ak kontexste',
    'pricing.feature.advanced_memory': 'Xam-xam bu mag',
    'pricing.feature.templates': 'Royuwaay',
    'pricing.feature.all_templates': 'Royuwaay yépp',
    'pricing.feature.priority': 'Tontu yu gën a gaawe',
    'pricing.feature.advanced_planning': 'Royoowal bu mag',
    'pricing.feature.early_access': 'Jëkk ci yoon bu bees ci gànaaw',
    'pricing.feature.all_modes': 'Yoon yu spécial yépp',
    'pricing.footer_note': 'Plan yépp ngi am jëkk ci yëf yu jàng Al-Qur\'an, laaj Fatwa ak ndigël bu Islam.'
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { user } = useAuth();

  const readStored = (): Language => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('G�stuSaDine-language') as Language;
      if (saved && ['en', 'fr', 'wo'].includes(saved)) return saved;
    }
    // Firebase User doesn't have user_metadata on the client object directly
    // would need to fetch from Firestore profile
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(readStored);

  // Sync document lang and persist
  useEffect(() => {
    document.documentElement.lang = language;
    if (typeof window !== 'undefined') {
      localStorage.setItem('G�stuSaDine-language', language);
    }
    if (user) {
      // Profile updates are now handled via Firestore in AuthContext or Profile settings
    }
  }, [language, user]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const current = (translations as Record<string, Record<string, string>>)[language];
    const translate = (dict?: Record<string, string>) => {
      const value = dict?.[key];
      if (!value) return undefined;
      if (!params) return value;
      return Object.keys(params).reduce((acc, paramKey) => {
        const token = `{${paramKey}}`;
        return acc.replace(token, String(params[paramKey]));
      }, value);
    };

    const currentValue = translate(current);
    if (currentValue) return currentValue;

    const fallback = (translations as Record<string, Record<string, string>>).en;
    const fallbackValue = translate(fallback);
    if (fallbackValue) return fallbackValue;
    if (import.meta.env.DEV) {
      console.warn(`Missing translation key: ${key} for ${language}`);
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
